// packages/components/toast/snippets/Toast.solid.tsx
/** @jsxImportSource solid-js */
import { normalizeProps, useMachine } from '@destyler/solid'
import * as toast from '@destyler/toast'
import { createMemo, createUniqueId, For } from 'solid-js'
import { Portal } from 'solid-js/web'
import { ToastItem } from './Item.solid'
import './style.css'

export default function Toast() {
  const [state, send] = useMachine(
    toast.group.machine({
      id: createUniqueId(),
      placement: 'bottom-end',
      overlap: true,
      removeDelay: 200,
    }),
  )

  const api = createMemo(() => toast.group.connect(state as any, send, normalizeProps))

  function handleNotify() {
    api().create({
      title: 'What to say?',
      type: 'info',
    })
  }

  return (
    <>
      <button
        class="btn"
        onClick={handleNotify}
      >
        Notify
      </button>

      <Portal>
        <For each={api().getPlacements()}>
          {placement => (
            <div data-layout="sinppets" {...api().getGroupProps({ placement })}>
              <For each={api().getToastsByPlacement(placement)}>
                {toast => <ToastItem actor={toast} />}
              </For>
            </div>
          )}
        </For>
      </Portal>
    </>
  )
}

// packages/components/toast/snippets/Toast.svelte
<script lang="ts">
  import * as toast from '@destyler/toast'
  import {normalizeProps, useMachine, portal} from '@destyler/svelte'
  import ToastItem from './Item.svelte';
  import './style.css'


  const id = $props.id()

  const [state, send] = useMachine(
    toast.group.machine({
      id: id,
      placement: 'bottom-end',
      overlap: true,
      removeDelay: 200,
    }),
  )

  const api = $derived(toast.group.connect(state as any, send, normalizeProps))

  function handleNotify(){
    api.create({
      title: "What to say?",
      type: "info",
    })
  }
</script>

<button
  class="btn"
  onclick={handleNotify}
>
  Notify
</button>

<div use:portal>
  {#each api.getPlacements() as placement}
    <div key={placement} data-layout="sinppets" {...api.getGroupProps({ placement })}>
      {#each api.getToastsByPlacement(placement) as toast (toast.id)}
        <ToastItem actor={toast} />
      {/each}
    </div>
  {/each}
</div>
