// packages/components/switch/docs/snippets/switch/Switch.svelte
<script lang="ts">
  import * as switchs from '@destyler/switch'
  import { normalizeProps, useMachine } from '@destyler/svelte'
  import '@docs/styles/components/switch.css'

  const id = $props.id()

  const [state, send] = useMachine(switchs.machine({
    id,
    checked: true
  }))

  const api = $derived(switchs.connect(state, send, normalizeProps))
</script>

<label {...api.getRootProps()}>
  <input {...api.getHiddenInputProps()}>
  <span {...api.getControlProps()}>
    <span {...api.getThumbProps()}></span>
  </span>
</label>

// packages/components/switch/docs/snippets/switch/Switch.react.tsx
import { normalizeProps, useMachine } from '@destyler/react'
import * as switchs from '@destyler/switch'
import { useId } from 'react'
import '@docs/styles/components/switch.css'

export default function Switch() {
  const [state, send] = useMachine(switchs.machine({
    id: useId(),
    checked: true,
  }))

  const api = switchs.connect(state, send, normalizeProps)

  return (
    <label {...api.getRootProps()}>
      <input {...api.getHiddenInputProps()} />
      <span {...api.getControlProps()}>
        <span {...api.getThumbProps()} />
      </span>
    </label>
  )
}
