// packages/components/image/snippets/Image.react.tsx
import * as image from '@destyler/image'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'
import './style.css'

export default function Image() {
  const [state, send] = useMachine(image.machine({
    id: useId(),
  }))

  const api = image.connect(state, send, normalizeProps)

  return (
    <div {...api.getRootProps()}>
      <img
        alt="Destyler"
        src="https://github.com/destyler.png"
        {...api.getImageProps()}
      />
      <div {...api.getFallbackProps()}>
        EH
      </div>
    </div>
  )
}

// packages/components/image/snippets/Image.vue
<script setup lang="ts">
import * as image from '@destyler/image'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'
import './style.css'

const [state, send] = useMachine(image.machine({ id: useId() }))

const api = computed(() => image.connect(state.value, send, normalizeProps))
</script>

<template>
  <div v-bind="api.getRootProps()">
    <img
      alt="Destyler"
      src="https://github.com/destyler.png"
      v-bind="api.getImageProps()"
    >
    <div v-bind="api.getFallbackProps()">
      EH
    </div>
  </div>
</template>
