// examples/react/src/pages/label.tsx
import * as label from '@destyler/label'
import { normalizeProps, useMachine } from '@destyler/react'
import { StateVisualizer, Toolbar } from '@destyler/shared-private/react'
import { useId } from 'react'

export default function Label() {
  const id = useId()
  const [state, send] = useMachine(label.machine({ id }))
  const api = label.connect(state, send, normalizeProps)

  return (
    <>
      <label {...api.getRootProps()}>
        text
      </label>
      <Toolbar>
        <StateVisualizer state={state} />
      </Toolbar>
    </>
  )
}

// examples/vue/src/pages/label.vue
<script setup lang="ts">
import * as label from '@destyler/label'
import { StateVisualizer, Toolbar } from '@destyler/shared-private/vue'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'

const [state, send] = useMachine(label.machine({ id: useId() }))

const api = computed(() => label.connect(state.value, send, normalizeProps))
</script>

<template>
  <label v-bind="api.getRootProps()">
    text
  </label>
  <Toolbar>
    <StateVisualizer :state="state" />
  </Toolbar>
</template>
