// document/src/snippets/Sinppets.vue
<script setup lang="ts">
import AspectRatio from '@component/aspect-ratio/snippets/AspectRatio.vue'
import Breadcrumbs from '@component/breadcrumbs/snippets/Breadcrumbs.vue'
import Calendar from '@component/calendar/snippets/Calendar.vue'
import Carousel from '@component/carousel/snippets/Carousel.vue'
import Checkbox from '@component/checkbox/snippets/Checkbox.vue'
import Clipboard from '@component/clipboard/snippets/Clipboard.vue'
import Collapse from '@component/collapse/snippets/Collapse.vue'
import Collapsible from '@component/collapsible/snippets/Collapsible.vue'
import ColorPicker from '@component/color-picker/snippets/ColorPicker.vue'
import Combobox from '@component/combobox/snippets/Combobox.vue'
import Dialog from '@component/dialog/snippets/Dialog.vue'
import Dynamic from '@component/dynamic/snippets/Dynamic.vue'
import Edit from '@component/edit/snippets/Edit.vue'
import FileUpload from '@component/file-upload/snippets/FileUpload.vue'
import Floatingpanel from '@component/floating-panel/snippets/FloatingPanel.vue'
import HoverCard from '@component/hover-card/snippets/HoverCard.vue'
import Image from '@component/image/snippets/Image.vue'
import Label from '@component/label/snippets/Label.vue'
import ContentMenu from '@component/menu/snippets/content-menu/ContentMenu.vue'
import Menu from '@component/menu/snippets/menu/Menu.vue'
import NumberInput from '@component/number-input/snippets/NumberInput.vue'
import OtpInput from '@component/otp-input/snippets/OtpInput.vue'
import Pagination from '@component/pagination/snippets/Pagination.vue'
import Popover from '@component/popover/snippets/Popover.vue'
import Progress from '@component/progress/snippets/Progress.vue'
import QrCode from '@component/qr-code/snippets/QRCode.vue'
import Radio from '@component/radio/snippets/Radio.vue'
import ScrollArea from '@component/scroll-area/snippets/ScrollArea.vue'
import Select from '@component/select/snippets/Select.vue'
import Separator from '@component/separator/snippets/Separator.vue'
import Signature from '@component/signature/snippets/Signature.vue'
import Slider from '@component/slider/snippets/Slider.vue'
import Splitter from '@component/splitter/snippets/Splitter.vue'
import Steps from '@component/steps/snippets/Steps.vue'
import Switch from '@component/switch/snippets/Switch.vue'
import Tabs from '@component/tabs/snippets/Tabs.vue'
import Timer from '@component/timer/snippets/Timer.vue'
import Toast from '@component/toast/snippets/Toast.vue'
import Toggle from '@component/toggle/snippets/Toggle.vue'
import Tooltip from '@component/tooltip/snippets/Tooltip.vue'
import Tour from '@component/tour/snippets/Tour.vue'
import Tree from '@component/tree/snippets/Tree.vue'

const props = defineProps<{
  name: string
}>()
</script>

<template>
  <div data-layout="sinppets" class="min-w-150px flex justify-center items-center mt-0!">
    <Checkbox v-if="props.name === 'checkbox'" />
    <Calendar v-if="props.name === 'calendar'" />
    <Collapse v-if="props.name === 'collapse'" class="w-450px!" />
    <Combobox v-if="props.name === 'combobox'" />
    <Dynamic v-if="props.name === 'dynamic'" />
    <Label v-if="props.name === 'label'" />
    <OtpInput v-if="props.name === 'otp-input'" />
    <Radio v-if="props.name === 'radio'" />
    <Select v-if="props.name === 'select'" />
    <Slider v-if="props.name === 'slider'" class="w-450px!" />
    <Switch v-if="props.name === 'switch'" />
    <Toggle v-if="props.name === 'toggle'" />
    <!-- <Calendar v-if="props.name === 'calendar'" /> -->
    <QrCode v-if="props.name === 'qr-code'" />
    <Collapsible v-if="props.name === 'collapsible'" />
    <Dialog v-if="props.name === 'dialog'" />
    <Image v-if="props.name === 'image'" />
    <HoverCard v-if="props.name === 'hover-card'" />
    <AspectRatio v-if="props.name === 'aspect-ratio'" />
    <Breadcrumbs v-if="props.name === 'breadcrumbs'" />
    <Carousel v-if="props.name === 'carousel'" />
    <Clipboard v-if="props.name === 'clipboard'" />
    <ColorPicker v-if="props.name === 'color-picker'" />
    <Separator v-if="props.name === 'separator'" />
    <Edit v-if="props.name === 'edit'" />
    <FileUpload v-if="props.name === 'file-upload'" />
    <Floatingpanel v-if="props.name === 'floating-panel'" />
    <Menu v-if="props.name === 'menu'" />
    <ContentMenu v-if="props.name === 'content-menu'" />
    <NumberInput v-if="props.name === 'number-input'" />
    <Pagination v-if="props.name === 'pagination'" />
    <Popover v-if="props.name === 'popover'" />
    <Progress v-if="props.name === 'progress'" class="w-450px!" />
    <Signature v-if="props.name === 'signature'" />
    <Splitter v-if="props.name === 'splitter'" />
    <Steps v-if="props.name === 'steps'" class="w-450px!" />
    <Tabs v-if="props.name === 'tabs'" />
    <Timer v-if="props.name === 'timer'" />
    <Tooltip v-if="props.name === 'tooltip'" />
    <Tree v-if="props.name === 'tree'" />
    <Toast v-if="props.name === 'toast'" />
    <Tour v-if="props.name === 'tour'" />
    <ScrollArea v-if="props.name === 'scroll-area'" />
  </div>
</template>

// document/src/snippets/Sinppets.svelte
<script lang="ts">
  import AspectRatio from '@component/aspect-ratio/snippets/AspectRatio.svelte'
  import Breadcrumbs from '@component/breadcrumbs/snippets/Breadcrumbs.svelte'
  import Carousel from '@component/carousel/snippets/Carousel.svelte'
  import Checkbox from '@component/checkbox/snippets/Checkbox.svelte'
  import Clipboard from '@component/clipboard/snippets/Clipboard.svelte'
  import Collapse from '@component/collapse/snippets/Collapse.svelte'
  import Collapsible from '@component/collapsible/snippets/Collapsible.svelte'
  import ColorPicker from '@component/color-picker/snippets/ColorPicker.svelte'
  import Combobox from '@component/combobox/snippets/Combobox.svelte'
  import Dialog from '@component/dialog/snippets/Dialog.svelte'
  import Dynamic from '@component/dynamic/snippets/Dynamic.svelte'
  import Edit from '@component/edit/snippets/Edit.svelte'
  import FileUpload from '@component/file-upload/snippets/FileUpload.svelte'
  import HoverCard from '@component/hover-card/snippets/HoverCard.svelte'
  import Image from '@component/image/snippets/Image.svelte'
  import Label from '@component/label/snippets/Label.svelte'
  import ContentMenu from '@component/menu/snippets/content-menu/ContentMenu.svelte'
  import Menu from '@component/menu/snippets/menu/Menu.svelte'
  import NumberInput from '@component/number-input/snippets/NumberInput.svelte'
  import OtpInput from '@component/otp-input/snippets/OtpInput.svelte'
  import Pagination from '@component/pagination/snippets/Pagination.svelte'
  import Popover from '@component/popover/snippets/Popover.svelte'
  import Progress from '@component/progress/snippets/Progress.svelte'
  import QrCode from '@component/qr-code/snippets/QRCode.svelte'
  import Radio from '@component/radio/snippets/Radio.svelte'
  import Select from '@component/select/snippets/Select.svelte'
  import Separator from '@component/separator/snippets/Separator.svelte'
  import Signature from '@component/signature/snippets/Signature.svelte'
  import Slider from '@component/slider/snippets/Slider.svelte'
  import Splitter from '@component/splitter/snippets/Splitter.svelte'
  import Steps from '@component/steps/snippets/Steps.svelte'
  import Switch from '@component/switch/snippets/Switch.svelte'
  import Tabs from '@component/tabs/snippets/Tabs.svelte'
  import Timer from '@component/timer/snippets/Timer.svelte'
  import Toggle from '@component/toggle/snippets/Toggle.svelte'
  import Tooltip from '@component/tooltip/snippets/Tooltip.svelte'
  import Tree from '@component/tree/snippets/Tree.svelte'
  import Calendar from '@component/calendar/snippets/Calendar.svelte'
  import Toast from '@component/toast/snippets/Toast.svelte'
  import Tour from '@component/tour/snippets/Tour.svelte'
  import FloatingPanel from '@component/floating-panel/snippets/FloatingPanel.svelte'
  import ScrollArea from '@component/scroll-area/snippets/ScrollArea.svelte'

  export let name: string;
</script>

<div data-layout="sinppets" class="min-w-150px flex justify-center items-center mt-0!">
  {#if name === 'checkbox'}
    <Checkbox />
  {/if}
  {#if name === 'collapse'}
    <Collapse className="w-450px!" />
  {/if}
  {#if name === 'combobox'}
    <Combobox />
  {/if}
  {#if name === 'calendar'}
    <Calendar />
  {/if}
  {#if name === 'dynamic'}
    <Dynamic />
  {/if}
  {#if name === 'label'}
    <Label />
  {/if}
  {#if name === 'otp-input'}
    <OtpInput />
  {/if}
  {#if name === 'radio'}
    <Radio />
  {/if}
  {#if name === 'select'}
    <Select />
  {/if}
  {#if name === 'slider'}
    <Slider className="w-450px!" />
  {/if}
  {#if name === 'switch'}
    <Switch />
  {/if}
  {#if name === 'toggle'}
    <Toggle />
  {/if}
  {#if name === 'qr-code'}
    <QrCode />
  {/if}
  {#if name === 'collapsible'}
    <Collapsible />
  {/if}
  {#if name === 'dialog'}
    <Dialog />
  {/if}
  {#if name === 'image'}
    <Image />
  {/if}
  {#if name === 'hover-card'}
    <HoverCard />
  {/if}
  {#if name === 'aspect-ratio'}
    <AspectRatio />
  {/if}
  {#if name === 'breadcrumbs'}
    <Breadcrumbs />
  {/if}
  {#if name === 'carousel'}
    <Carousel />
  {/if}
  {#if name === 'clipboard'}
    <Clipboard />
  {/if}
  {#if name === 'color-picker'}
    <ColorPicker />
  {/if}
  {#if name === 'separator'}
    <Separator />
  {/if}
  {#if name === 'edit'}
    <Edit />
  {/if}
  {#if name === 'file-upload'}
    <FileUpload />
  {/if}
  {#if name === 'floating-panel'}
    <FloatingPanel />
  {/if}
  {#if name === 'menu'}
    <Menu />
  {/if}
  {#if name === 'content-menu'}
    <ContentMenu />
  {/if}
  {#if name === 'number-input'}
    <NumberInput />
  {/if}
  {#if name === 'pagination'}
    <Pagination />
  {/if}
  {#if name === 'popover'}
    <Popover />
  {/if}
  {#if name === 'progress'}
    <Progress />
  {/if}
  {#if name === 'signature'}
    <Signature />
  {/if}
  {#if name === 'splitter'}
    <Splitter />
  {/if}
  {#if name === 'steps'}
    <Steps className="w-450px!" />
  {/if}
  {#if name === 'tabs'}
    <Tabs />
  {/if}
  {#if name === 'timer'}
    <Timer />
  {/if}
  {#if name === 'tooltip'}
    <Tooltip />
  {/if}
  {#if name === 'tree'}
    <Tree />
  {/if}
  {#if name === 'toast'}
    <Toast />
  {/if}
  {#if name === 'tour'}
    <Tour />
  {/if}
  {#if name === 'scroll-area'}
    <ScrollArea />
  {/if}
</div>
