// document/src/snippets/radio/svelte/tailwind/index.svelte
<script lang="ts">
  import * as radio from '@destyler/radio'
  import { normalizeProps, useMachine } from '@destyler/svelte'

  const items = [
    { id: 'default', label: 'Default' },
    { id: 'comfortable', label: 'Comfortable' },
    { id: 'compact', label: 'Compact' },
  ]

  const id = $props.id()

  const [state, send] = useMachine(radio.machine({
    id,
    value: 'default',
  }))

  const api = $derived(radio.connect(state, send, normalizeProps))
</script>

<div {...api.getRootProps()} class="grid gap-2">
  {#each items as opt (opt.id)}
    <div class="flex items-center space-x-3">
      <label
        {...api.getItemProps({ value: opt.id })}
        class="flex items-center space-x-2 cursor-pointer"
      >
        <div class="relative">
          <input
            {...api.getItemHiddenInputProps({ value: opt.id })}
            class="peer sr-only"
          >
          <div
            {...api.getItemControlProps({ value: opt.id })}
            class="h-4 w-4 rounded-full border border-primary shadow focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:border-primary data-[state=checked]:bg-primary"
          ></div>
        </div>
        <span
          {...api.getItemTextProps({ value: opt.id })}
          class="text-sm font-medium leading-none text-foreground peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
        >
          {opt.label}
        </span>
      </label>
    </div>
  {/each}
</div>

// document/src/snippets/checkbox/react/tailwind/index.tsx
/** @jsxImportSource react */
import * as checkbox from '@destyler/checkbox'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'

export default function Checkbox() {
  const [state, send] = useMachine(checkbox.machine({ id: useId() }))
  const api = checkbox.connect(state, send, normalizeProps)

  return (
    <label {...api.getRootProps()} className="flex items-center gap-2 cursor-pointer">
      <div
        {...api.getControlProps()}
        className="peer h-4 w-4 shrink-0 rounded-sm border border-primary
          shadow-sm focus-visible:outline-none focus-visible:ring-2
          focus-visible:ring-ring focus-visible:ring-offset-2
          disabled:cursor-not-allowed disabled:opacity-50
          data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground
          flex items-center justify-center"
      >
        {api.checked && <div className="i-carbon-checkmark w-3 h-3" />}
      </div>
      <span {...api.getLabelProps()} className="text-sm font-medium text-foreground leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
        Input is
        {' '}
        {api.checked ? ' checked' : ' unchecked'}
      </span>

      <input {...api.getHiddenInputProps()} />
    </label>
  )
}
