// shared/src/react/components/Layout.tsx
export function Layout({ children }: { children?: React.ReactNode }) {
  return (
    <>
      <style>
        {`.layout{
          --toolbar-width: 400px;
          display: flex;
          height: 100vh;
          overflow: hidden;
        }

        .layout-root {
          flex: auto;
          display: flex;
          gap: 10px;
          position: relative;
          flex-direction: column;
          align-items: flex-start;
          padding: 40px;
          padding-right: calc(40px + var(--toolbar-width, 400px));
          overflow-y: auto;
        }`}
      </style>
      <div data-story="book" className="layout">
        <main className="layout-root">
          {children}
        </main>
      </div>
    </>
  )
}

// shared/src/solid/components/Layout.tsx
/** @jsxImportSource solid-js */
import type { JSX } from 'solid-js'

export function Layout(props: { children: JSX.Element }) {
  return (
    <>
      <style>
        {`.layout{
          --toolbar-width: 400px;
          display: flex;
          height: 100vh;
          overflow: hidden;
        }

        .layout-root {
          flex: auto;
          display: flex;
          gap: 10px;
          position: relative;
          flex-direction: column;
          align-items: flex-start;
          padding: 40px;
          padding-right: calc(40px + var(--toolbar-width, 400px));
          overflow-y: auto;
        }`}
      </style>
      <div data-story="book" class="layout">
        <main class="layout-root">
          {props.children}
        </main>
      </div>
    </>
  )
}
