// shared/src/react/components/StateVisualizer.tsx
import { highlightState } from '@destyler/stringify'

interface StateVisualizerProps {
  state: any
  label?: string
  omit?: string[]
}

export function StateVisualizer({ state, label, omit }: StateVisualizerProps) {
  return (
    <div className="viz">
      <pre>
        <details open>
          <summary>{label || 'Visualizer'}</summary>
          <div dangerouslySetInnerHTML={{ __html: highlightState(state, omit) }} />
        </details>
      </pre>
    </div>
  )
}

// examples/svelte/src/components/state-visualizer.svelte
<script lang="ts">
  import { highlightState } from "@destyler/stringify"

  interface StateVisualizerProps {
    state: Record<string, any>
    label?: string
    omit?: string[]
  }

  const { label, state: currentState, omit }: StateVisualizerProps = $props()
</script>

<div class="viz">
  <pre>
    <details open>
        <summary>{label || "Visualizer"}</summary>
        <div>{@html highlightState($state.snapshot(currentState), omit)}</div>
    </details>
  </pre>
</div>
