// examples/vue/src/components/tool/Toolbar.vue
<script setup lang="ts">
import { dataAttr } from '@zag-js/dom-query'
import { ref, useSlots } from 'vue'

const props = defineProps<{
  viz?: boolean
}>()

const slots = useSlots()

const controls = !!slots.controls
const activeState = ref(props.viz ? 1 : !controls ? 1 : 0)
</script>

<template>
  <div class="toolbar z-10 fixed right-0 top-0 bottom-0 w-80">
    <nav>
      <button
        v-if="controls"
        :data-active="dataAttr(activeState === 0)"
        @click="() => (activeState = 0)"
      >
        Controls
      </button>

      <button
        :data-active="dataAttr(activeState === 1)"
        @click="() => (activeState = 1)"
      >
        Visualizer
      </button>
    </nav>
    <div>
      <div v-if="controls" data-content :data-active="dataAttr(activeState === 0)">
        <slot name="controls" />
      </div>

      <div data-content :data-active="dataAttr(activeState === 1)">
        <slot />
      </div>
    </div>
  </div>
</template>

// examples/react/src/components/tool/Toolbar.tsx
import type { ReactNode } from 'react'
import { dataAttr } from '@zag-js/dom-query'
import { useState } from 'react'

interface ToolbarProps {
  viz?: boolean
  children?: ReactNode
  controls?: ReactNode
}

export function Toolbar({ viz, children, controls }: ToolbarProps) {
  const hasControls = !!controls
  const [activeState, setActiveState] = useState(viz ? 1 : !hasControls ? 1 : 0)

  return (
    <div className="toolbar z-10 fixed right-0 top-0 bottom-0 w-80">
      <nav>
        {hasControls && (
          <button
            data-active={dataAttr(activeState === 0)}
            onClick={() => setActiveState(0)}
          >
            Controls
          </button>
        )}
        <button
          data-active={dataAttr(activeState === 1)}
          onClick={() => setActiveState(1)}
        >
          Visualizer
        </button>
      </nav>
      <div>
        {hasControls && (
          <div data-content data-active={dataAttr(activeState === 0)}>
            {controls}
          </div>
        )}
        <div data-content data-active={dataAttr(activeState === 1)}>
          {children}
        </div>
      </div>
    </div>
  )
}
