// packages/components/signature/examples/vue/Signature.vue
<script setup lang="ts">
import { signatureControls } from '@destyler/shared-private'
import { Controls, Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/vue'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, ref, useId } from 'vue'
import * as signature from '../../index'
import '../style.css'

const url = ref('')
const setUrl = (v: string) => (url.value = v)

const controls = useControls(signatureControls)

const [state, send] = useMachine(signature.machine({ id: useId() }), {
  context: controls.context,
})

const api = computed(() => signature.connect(state.value, send, normalizeProps))
</script>

<template>
  <Layout>
    <main>
      <div v-bind="api.getRootProps()">
        <label v-bind="api.getLabelProps()">Signature Pad</label>

        <div v-bind="api.getControlProps()">
          <svg v-bind="api.getSegmentProps()">
            <path v-for="(path, i) of api.paths" :key="i" v-bind="api.getSegmentPathProps({ path })" />
            <path v-if="api.currentPath" v-bind="api.getSegmentPathProps({ path: api.currentPath })" />
          </svg>
          <div v-bind="api.getGuideProps()" />
        </div>

        <button v-bind="api.getClearTriggerProps()">
          x
        </button>
      </div>

      <button
        @click="
          () => {
            api.getDataUrl('image/png').then(setUrl)
          }
        "
      >
        Show Image
      </button>
      <img v-if="url" data-part="preview" alt="signature" :src="url">
    </main>

    <Toolbar>
      <StateVisualizer :state="state" :omit="['currentPoints', 'currentPath', 'paths']" />
      <template #controls>
        <Controls :control="controls" />
      </template>
    </Toolbar>
  </Layout>
</template>

// packages/components/signature/examples/react/Signature.react.tsx
import { normalizeProps, useMachine } from '@destyler/react'
import { signatureControls } from '@destyler/shared-private'
import { Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/react'
import { useId, useState } from 'react'
import * as signaturePad from '../../index'
import '../style.css'

export default function Page() {
  const [url, setUrl] = useState('')

  const controls = useControls(signatureControls)

  const [state, send] = useMachine(
    signaturePad.machine({
      id: useId(),
      onDrawEnd(details) {
        details.getDataUrl('image/png').then(setUrl)
      },
      drawing: {
        fill: 'red',
        size: 4,
        simulatePressure: true,
      },
    }),
    { context: controls.context },
  )

  const api = signaturePad.connect(state, send, normalizeProps)

  return (
    <Layout>
      <main>
        <div {...api.getRootProps()}>
          <label {...api.getLabelProps()}>Signature Pad</label>

          <div {...api.getControlProps()}>
            <svg {...api.getSegmentProps()}>
              {api.paths.map((path, i) => (
                <path key={i} {...api.getSegmentPathProps({ path })} />
              ))}
              {api.currentPath && <path {...api.getSegmentPathProps({ path: api.currentPath })} />}
            </svg>

            <div {...api.getGuideProps()} />
          </div>

          <button {...api.getClearTriggerProps()}>
            x
          </button>
        </div>

        <button
          onClick={() => {
            api.getDataUrl('image/png').then(setUrl)
          }}
        >
          Show Image
        </button>
        {url && <img data-part="preview" alt="signature" src={url} />}
      </main>

      <Toolbar controls={controls.ui()}>
        <StateVisualizer state={state} omit={['currentPoints', 'currentPath', 'paths']} />
      </Toolbar>
    </Layout>
  )
}
