// packages/frameworks/react/src/hooks/use-service.ts
import type { AnyEventObject, EventObject, HookOptions, MachineSrc, StateInit, StateSchema } from '@destyler/xstate'
import { useRef } from 'react'
import { useConstant } from './use-constant'
import { useSafeLayoutEffect } from './use-layout-effect'

export function useService<
  TContext extends Record<string, any>,
  TState extends StateSchema,
  TEvent extends EventObject = AnyEventObject,
>(machine: MachineSrc<TContext, TState, TEvent>, options?: HookOptions<TContext, TState, TEvent>) {
  const { state: hydratedState, context, actions } = options ?? {}

  const service = useConstant(() => {
    const instance = typeof machine === 'function' ? machine() : machine
    if (context)
      instance.setContext(context)
    if (actions)
      instance.setOptions({ actions })
    instance._created()
    return instance
  })

  const snapshotRef = useRef<StateInit<TContext, TState>>(undefined)

  useSafeLayoutEffect(() => {
    const stateInit = hydratedState ?? snapshotRef.current
    service.start(stateInit)
    return () => {
      service.stop()
    }
  }, [])

  return service
}

// packages/frameworks/solid/src/hooks/use-service.ts
import type { AnyEventObject, EventObject, MachineSrc, StateSchema } from '@destyler/xstate'
import type { MachineOptions } from '../types'
import { onCleanup, onMount } from 'solid-js'

export function useService<
  TContext extends Record<string, any>,
  TState extends StateSchema,
  TEvent extends EventObject = AnyEventObject,
>(machine: MachineSrc<TContext, TState, TEvent>, options?: MachineOptions<TContext, TState, TEvent>) {
  const { state: hydratedState, context, actions } = options ?? {}

  const service = (() => {
    const instance = typeof machine === 'function' ? machine() : machine
    const ctx = typeof context === 'function' ? context() : context
    if (ctx)
      instance.setContext(ctx)
    if (actions)
      instance.setOptions({ actions })
    instance._created()
    return instance
  })()

  onMount(() => {
    service.start(hydratedState)

    onCleanup(() => {
      service.stop()
    })
  })

  return service
}
