// packages/components/qr-code/docs/snippets/qr-code/QRCode.react.tsx
import * as qrCode from '@destyler/qr-code'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'
import '@docs/styles/components/qr-code.css'

export default function QrCode() {
  const [state, send] = useMachine(
    qrCode.machine({
      id: useId(),
      value: 'https://destyler.org',
      encoding: {
        ecc: 'H',
      },
    }),
  )

  const api = qrCode.connect(state, send, normalizeProps)

  return (
    <>
      <div {...api.getRootProps()}>
        <svg {...api.getFrameProps()}>
          <path {...api.getPatternProps()} />
        </svg>
      </div>
    </>
  )
}

// packages/components/qr-code/docs/snippets/qr-code/QRCode.svelte
<script lang="ts">
  import * as qrCode from '@destyler/qr-code'
  import { normalizeProps, useMachine } from '@destyler/svelte'
  import '@docs/styles/components/qr-code.css'

  const id = $props.id()

  const [state, send] = useMachine(
    qrCode.machine({
      id,
      value: 'https://destyler.org',
      encoding: {
        ecc: 'H',
      },
    }),
  )

  const api = $derived(qrCode.connect(state, send, normalizeProps))
</script>

<div {...api.getRootProps()}>
  <svg {...api.getFrameProps()}>
    <path {...api.getPatternProps()} />
  </svg>
</div>
