// shared/src/svelte/components/state-visualizer.svelte
<script lang="ts">
  import { highlightState } from "@destyler/stringify"

  interface StateVisualizerProps {
    state: Record<string, any>
    label?: string
    omit?: string[]
  }

  const { label, state: currentState, omit }: StateVisualizerProps = $props()
</script>

<div class="viz">
  <pre>
    <details open>
        <summary>{label || "Visualizer"}</summary>
        <!-- svelte-ignore state_snapshot_uncloneable -->
        <div>{@html highlightState($state.snapshot(currentState), omit)}</div>
    </details>
  </pre>
</div>

// examples/vue/src/components/tool/StateVisualizer.vue
<script setup lang="ts">
import { highlightState } from '@destyler/stringify'
import { isRef } from 'vue'

const props = defineProps<{
  state: any
  label?: string
  omit?: string[]
}>()

const state = isRef(props.state) ? props.state.value : props.state
</script>

<template>
  <div class="viz">
    <pre>
        <details open>
          <summary> {{ props.label || "Visualizer" }} </summary>
          <div v-html="highlightState(state, props.omit)" />
        </details>
      </pre>
  </div>
</template>
