// document/src/snippets/image/Image.react.tsx
import * as image from '@destyler/image'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'
import '../../styles/components/image.css'

export default function Image() {
  const [state, send] = useMachine(image.machine({
    id: useId(),
  }))

  const api = image.connect(state, send, normalizeProps)

  return (
    <div {...api.getRootProps()}>
      <img
        alt="Destyler UI"
        src="https://github.com/destyler.png"
        {...api.getImageProps()}
      />
      <div {...api.getFallbackProps()}>
        EH
      </div>
    </div>
  )
}

// document/src/snippets/image/Image.svelte
<script lang="ts">
  import * as image from '@destyler/image'
  import { normalizeProps, useMachine } from '@destyler/svelte'
  import '../../styles/components/image.css'

  const id = $props.id()

  const [state, send] = useMachine(image.machine({ id }))

  const api = $derived(image.connect(state, send, normalizeProps))
</script>

<div {...api.getRootProps()}>
  <img
    alt="Destyler UI"
    src="https://github.com/destyler.png"
    {...api.getImageProps()}
  />
  <div {...api.getFallbackProps()}>
    EH
  </div>
</div>
