// packages/components/slider/docs/snippets/slider/Slider.svelte
<script lang="ts">
  import * as slider from '@destyler/slider'
  import { normalizeProps, useMachine } from '@destyler/svelte'
  import '@docs/styles/components/slider.css'

  const { className = '' } = $props()

  const id = $props.id()
  const [state, send] = useMachine(slider.machine({ id, value: [60] }))
  const api = $derived(slider.connect(state, send, normalizeProps))
</script>

<div {...api.getRootProps()} class={`${className}`}>
  <div {...api.getControlProps()}>
    <div {...api.getTrackProps()}>
      <div {...api.getRangeProps()}>
      </div>
    </div>
    {#each api.value as _, index (index)}
      <div {...api.getThumbProps({ index })}>
        <input {...api.getHiddenInputProps({ index })}>
      </div>
    {/each}
  </div>
</div>

// packages/components/slider/docs/snippets/slider/Slider.react.tsx
import { normalizeProps, useMachine } from '@destyler/react'
import * as slider from '@destyler/slider'
import { useId } from 'react'
import '@docs/styles/components/slider.css'

export default function Slider({ className = '' }: { className?: string }) {
  const [state, send] = useMachine(slider.machine({
    id: useId(),
    value: [60],
  }))

  const api = slider.connect(state, send, normalizeProps)

  return (
    <div {...api.getRootProps()} className={`${className}`}>
      <div {...api.getControlProps()}>
        <div {...api.getTrackProps()}>
          <div {...api.getRangeProps()} />
        </div>
        {api.value.map((_, index) => (
          <div key={index} {...api.getThumbProps({ index })}>
            <input {...api.getHiddenInputProps({ index })} />
          </div>
        ))}
      </div>
    </div>
  )
}
