// document/src/snippets/hover-card/HoverCard.svelte
<script lang="ts">
  import * as hoverCard from '@destyler/hover-card'
  import { normalizeProps, useMachine, portal } from '@destyler/svelte'

  const id = $props.id()

  const [state, send] = useMachine(hoverCard.machine({ id }))

  const api = $derived(hoverCard.connect(state, send, normalizeProps))
</script>

<div class=" mt-0!">
  <a
    href="https://twitter.com/elonehoo"
    target="_blank"
    {...api.getTriggerProps()}
    class="btn  no-underline!"
  >
    Hover
  </a>

  {#if api.open}
    <div use:portal>
      <div {...api.getPositionerProps()}>
        <div
          {...api.getContentProps()}
          class="z-50 w-64 rounded-md border border-border! bg-popover p-4 text-popover-foreground shadow-md outline-none animate-in zoom-in-90"
        >
          <div class="flex gap-4 mt-0!">
            <img
              src="https://github.com/elonehoo.png"
              alt="Profile"
              class="h-12 w-12 rounded-full border border-border!"
            />
            <div class="space-y-1">
              <h4 class="text-sm font-semibold">
                elonehoo
              </h4>
              <p class="text-sm text-muted-foreground">
                Frontend Developer
              </p>
            </div>
          </div>
          <div class="mt-4 text-sm text-muted-foreground">
            I hope every sunny afternoon can be wasted.
          </div>
          <div class="mt-4 flex items-center text-sm text-muted-foreground">
            <div class="w-4 h-4 i-carbon:logo-x mr-2" ></div>
            @elonehoo
          </div>
        </div>
      </div>
    </div>

  {/if}
</div>

// document/src/snippets/hover-card/HoverCard.react.tsx
import * as hoverCard from '@destyler/hover-card'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'
import { createPortal } from 'react-dom'

export default function HoverCard() {
  const [state, send] = useMachine(hoverCard.machine({
    id: useId(),
  }))

  const api = hoverCard.connect(state, send, normalizeProps)

  return (
    <div className=" mt-0!">
      <a
        href="https://twitter.com/elonehoo"
        target="_blank"
        {...api.getTriggerProps()}
        className="btn no-underline!"
      >
        Hover
      </a>

      {api.open && createPortal(
        <div {...api.getPositionerProps()}>
          <div
            {...api.getContentProps()}
            className="z-50 w-64 rounded-md border border-border! bg-popover p-4 text-popover-foreground shadow-md outline-none animate-in zoom-in-90"
          >
            <div className="flex gap-4 mt-0!">
              <img
                src="https://github.com/elonehoo.png"
                alt="Profile"
                className="h-12 w-12 rounded-full border border-border!"
              />
              <div className="space-y-1">
                <h4 className="text-sm font-semibold">elonehoo</h4>
                <p className="text-sm text-muted-foreground">Frontend Developer</p>
              </div>
            </div>
            <div className="mt-4 text-sm text-muted-foreground">
              I hope every sunny afternoon can be wasted.
            </div>
            <div className="mt-4 flex items-center text-sm text-muted-foreground">
              <div className="w-4 h-4 i-carbon:logo-x mr-2" />
              @elonehoo
            </div>
          </div>
        </div>,
        document.body,
      )}
    </div>
  )
}
