// document/src/snippets/qr-code/QRCode.react.tsx
import * as qrCode from '@destyler/qr-code'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'


export default function QrCode() {

  const [state, send] = useMachine(
    qrCode.machine({
      id: useId(),
      value: 'https://destyler.org',
      encoding: {
        ecc: 'H',
      },
    }),
  )

  const api = qrCode.connect(state, send, normalizeProps)

  return (
    <>
      <div {...api.getRootProps()} className="size-135px">
        <svg {...api.getFrameProps()} className="size-135px bg-background">
          <path {...api.getPatternProps()} className='fill-primary' />
        </svg>
      </div>
    </>
  )
}

// document/src/snippets/qr-code/QRCode.svelte
<script lang="ts">
  import * as qrCode from '@destyler/qr-code'
  import { normalizeProps, useMachine } from '@destyler/svelte'

  const id = $props.id()

  const [state, send] = useMachine(
    qrCode.machine({
      id,
      value: 'https://destyler.org',
      encoding: {
        ecc: 'H',
      },
    }),
  )

  const api = $derived(qrCode.connect(state, send, normalizeProps))
</script>

<div {...api.getRootProps()} class="size-135px">
  <svg {...api.getFrameProps()} class="size-135px bg-background">
    <path {...api.getPatternProps()} class="fill-primary" />
  </svg>
</div>
