// document/src/snippets/timer/Timer.vue
<script setup lang="ts">
import * as timer from '@destyler/timer'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'

const [state, send] = useMachine(
  timer.machine({
    id: useId(),
    countdown: true,
    autoStart: true,
    startMs: timer.parse({ days: 20, seconds: 1 }),
  }),
)

const api = computed(() => timer.connect(state.value, send, normalizeProps))
</script>

<template>
  <div v-bind="api.getRootProps()" class="inline-flex flex-col items-center justify-center mt-0!">
    <div v-bind="api.getAreaProps()" class="inline-flex items-center text-card-foreground shadow mt-0!">
      <div v-bind="api.getItemProps({ type: 'days' })" class="text-base tabular-nums mt-0!">
        {{ api.formattedTime.days }}
      </div>
      <div v-bind="api.getSeparatorProps()" class="text-muted-foreground mt-0!">
        :
      </div>
      <div v-bind="api.getItemProps({ type: 'hours' })" class="text-base tabular-nums mt-0!">
        {{ api.formattedTime.hours }}
      </div>
      <div v-bind="api.getSeparatorProps()" class="text-muted-foreground mt-0!">
        :
      </div>
      <div v-bind="api.getItemProps({ type: 'minutes' })" class="text-base tabular-nums mt-0!">
        {{ api.formattedTime.minutes }}
      </div>
      <div v-bind="api.getSeparatorProps()" class="text-muted-foreground mt-0!">
        :
      </div>
      <div v-bind="api.getItemProps({ type: 'seconds' })" class="text-base tabular-nums mt-0!">
        {{ api.formattedTime.seconds }}
      </div>
    </div>
  </div>
</template>

<style scoped>
[data-scope=timer][data-part=item] {
    height: 1em;
    display: inline-block;
    overflow-y: hidden;
    line-height: 1em;
    font-variation-settings: "tnum";
    text-align: center;
    &:before {
        position: relative;
        content: "00\a 01\a 02\a 03\a 04\a 05\a 06\a 07\a 08\a 09\a 10\a 11\a 12\a 13\a 14\a 15\a 16\a 17\a 18\a 19\a 20\a 21\a 22\a 23\a 24\a 25\a 26\a 27\a 28\a 29\a 30\a 31\a 32\a 33\a 34\a 35\a 36\a 37\a 38\a 39\a 40\a 41\a 42\a 43\a 44\a 45\a 46\a 47\a 48\a 49\a 50\a 51\a 52\a 53\a 54\a 55\a 56\a 57\a 58\a 59\a 60\a 61\a 62\a 63\a 64\a 65\a 66\a 67\a 68\a 69\a 70\a 71\a 72\a 73\a 74\a 75\a 76\a 77\a 78\a 79\a 80\a 81\a 82\a 83\a 84\a 85\a 86\a 87\a 88\a 89\a 90\a 91\a 92\a 93\a 94\a 95\a 96\a 97\a 98\a 99\a";
        white-space: pre;
        top: calc(var(--value) * -1em);
        text-align: center;
        transition: top 1s cubic-bezier(1,0,0,1);
    }
}
</style>

// document/src/snippets/timer/Timer.react.tsx
import { normalizeProps, useMachine } from '@destyler/react'
import * as timer from '@destyler/timer'
import { useId } from 'react'

export default function Timer() {
  const [state, send] = useMachine(
    timer.machine({
      id: useId(),
      countdown: true,
      autoStart: true,
      startMs: timer.parse({ days: 20, seconds: 1 }),
    }),
  )

  const api = timer.connect(state, send, normalizeProps)

  return (
    <>
      <style>{`
        [data-scope=timer][data-part=item] {
          height: 1em;
          display: inline-block;
          overflow-y: hidden;
          line-height: 1em;
          font-variation-settings: "tnum";
          text-align: center;
        }
        [data-scope=timer][data-part=item]:before {
          position: relative;
          content: "00\\a 01\\a 02\\a 03\\a 04\\a 05\\a 06\\a 07\\a 08\\a 09\\a 10\\a 11\\a 12\\a 13\\a 14\\a 15\\a 16\\a 17\\a 18\\a 19\\a 20\\a 21\\a 22\\a 23\\a 24\\a 25\\a 26\\a 27\\a 28\\a 29\\a 30\\a 31\\a 32\\a 33\\a 34\\a 35\\a 36\\a 37\\a 38\\a 39\\a 40\\a 41\\a 42\\a 43\\a 44\\a 45\\a 46\\a 47\\a 48\\a 49\\a 50\\a 51\\a 52\\a 53\\a 54\\a 55\\a 56\\a 57\\a 58\\a 59\\a 60\\a 61\\a 62\\a 63\\a 64\\a 65\\a 66\\a 67\\a 68\\a 69\\a 70\\a 71\\a 72\\a 73\\a 74\\a 75\\a 76\\a 77\\a 78\\a 79\\a 80\\a 81\\a 82\\a 83\\a 84\\a 85\\a 86\\a 87\\a 88\\a 89\\a 90\\a 91\\a 92\\a 93\\a 94\\a 95\\a 96\\a 97\\a 98\\a 99\\a";
          white-space: pre;
          top: calc(var(--value) * -1em);
          text-align: center;
          transition: top 1s cubic-bezier(1,0,0,1);
        }
      `}</style>
      <div {...api.getRootProps()} className="inline-flex flex-col items-center justify-center mt-0!">
        <div {...api.getAreaProps()} className="inline-flex items-center text-card-foreground mt-0! shadow">
          <div {...api.getItemProps({ type: 'days' })} className="text-base tabular-nums mt-0!">
            {api.formattedTime.days}
          </div>
          <div {...api.getSeparatorProps()} className="text-muted-foreground mt-0!">
            :
          </div>
          <div {...api.getItemProps({ type: 'hours' })} className="text-base tabular-nums mt-0!">
            {api.formattedTime.hours}
          </div>
          <div {...api.getSeparatorProps()} className="text-muted-foreground mt-0!">
            :
          </div>
          <div {...api.getItemProps({ type: 'minutes' })} className="text-base tabular-nums mt-0!">
            {api.formattedTime.minutes}
          </div>
          <div {...api.getSeparatorProps()} className="text-muted-foreground mt-0!">
            :
          </div>
          <div {...api.getItemProps({ type: 'seconds' })} className="text-base tabular-nums mt-0!">
            {api.formattedTime.seconds}
          </div>
        </div>
      </div>
    </>
  )
}
