// packages/components/tree/examples/solid/TreeNode.solid.tsx
import type { Api } from '../../index'
/** @jsxImportSource solid-js */
import type { FileNode } from '../data'
import { createMemo, For, Show } from 'solid-js'

interface TreeNodeProps {
  node: FileNode
  indexPath: number[]
  api: Api
}

export default function TreeNode(props: TreeNodeProps) {
  const nodeProps = createMemo(() => ({ node: props.node, indexPath: props.indexPath }))
  const nodeState = createMemo(() => props.api.getNodeState(nodeProps()))

  return (
    <Show
      when={nodeState().isBranch}
      fallback={(
        <div {...props.api.getItemProps(nodeProps())}>
          <span {...props.api.getItemIndicatorProps(nodeProps())} />
          <span {...props.api.getItemTextProps(nodeProps())}>{props.node.name}</span>
        </div>
      )}
    >
      <div {...props.api.getBranchProps(nodeProps())}>
        <div {...props.api.getBranchControlProps(nodeProps())}>
          <span {...props.api.getBranchIndicatorProps(nodeProps())} />
          <span {...props.api.getBranchTextProps(nodeProps())}>{props.node.name}</span>
          <span class="tree-example__meta">
            {props.node.children?.length ?? 0}
            {' '}
            items
          </span>
        </div>
        <Show when={nodeState().expanded}>
          <div {...props.api.getBranchContentProps(nodeProps())}>
            <div {...props.api.getBranchIndentGuideProps(nodeProps())} />
            <For each={props.node.children ?? []}>
              {(child, index) => (
                <TreeNode node={child} indexPath={[...props.indexPath, index()]} api={props.api} />
              )}
            </For>
          </div>
        </Show>
      </div>
    </Show>
  )
}

// packages/components/tree/examples/svelte/TreeNode.svelte
<script lang="ts">
  import type { FileNode } from '../data'
  import type { Api } from '../../index'

  export let node: FileNode
  export let indexPath: number[]
  export let api: Api

  $: nodeProps = { node, indexPath }
  $: nodeState = api.getNodeState(nodeProps)
  $: childCount = node.children?.length ?? 0
</script>

{#if nodeState.isBranch}
  <div {...api.getBranchProps(nodeProps)}>
    <div {...api.getBranchControlProps(nodeProps)}>
      <span {...api.getBranchIndicatorProps(nodeProps)}></span>
      <span {...api.getBranchTextProps(nodeProps)}>{node.name}</span>
      <span class="tree-example__meta">{childCount} items</span>
    </div>
    {#if nodeState.expanded}
      <div {...api.getBranchContentProps(nodeProps)}>
        <div {...api.getBranchIndentGuideProps(nodeProps)}></div>
        {#each node.children ?? [] as child, index}
          <svelte:self node={child} indexPath={[...indexPath, index]} {api} />
        {/each}
      </div>
    {/if}
  </div>
{:else}
  <div {...api.getItemProps(nodeProps)}>
    <span {...api.getItemIndicatorProps(nodeProps)}></span>
    <span {...api.getItemTextProps(nodeProps)}>{node.name}</span>
  </div>
{/if}
