// packages/components/tree/examples/react/Tree.react.tsx
import type { FileNode } from '../data'
import { normalizeProps, useMachine } from '@destyler/react'
import { treeControls } from '@destyler/shared-private'
import { Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/react'
import { useId, useMemo } from 'react'
import * as tree from '../../index'
import { createFileTreeCollection, defaultExpandedBranches } from '../data'
import TreeNode from './TreeNode.react'
import '../style.css'

export default function TreeExample() {
  const controls = useControls(treeControls)
  const collection = useMemo(() => createFileTreeCollection(), [])

  const { dir, selectionMode, openOnClick } = controls.context

  const controlContext = useMemo(
    () => ({
      dir,
      selectionMode,
      expandOnClick: openOnClick,
    }),
    [dir, selectionMode, openOnClick],
  )

  const [state, send] = useMachine(
    tree.machine({
      id: useId(),
      collection,
      defaultExpandedValue: defaultExpandedBranches,
    }),
    {
      context: controlContext,
    },
  )

  const api = tree.connect(state, send, normalizeProps)

  return (
    <Layout>
      <main className="tree-example">
        <section className="tree-example__card">
          <div className="tree-example__header">
            <h3 {...api.getLabelProps()}>Project files</h3>
            <span className="tree-example__meta">
              {api.expandedValue.length}
              {' '}
              open folders
            </span>
          </div>

          <div className="tree-example__actions">
            <button type="button" onClick={() => api.expand()}>Expand all</button>
            <button type="button" onClick={() => api.collapse()}>Collapse all</button>
            <button type="button" onClick={() => api.select()}>Select all</button>
            <button type="button" onClick={() => api.deselect()}>Clear selection</button>
          </div>

          <div {...api.getRootProps()}>
            <div {...api.getTreeProps()}>
              {api.collection.rootNode.children?.map((node: FileNode, index: number) => (
                <TreeNode key={node.id} node={node} indexPath={[index]} api={api} />
              ))}
            </div>
          </div>
        </section>
      </main>

      <Toolbar controls={controls.ui()}>
        <StateVisualizer state={state} omit={['collection']} />
      </Toolbar>
    </Layout>
  )
}

// packages/components/tree/examples/svelte/Tree.svelte
<script lang="ts">
  import * as tree from '../../index'
  import { normalizeProps, useMachine } from '@destyler/svelte'
  import { treeControls } from '@destyler/shared-private'
  import { Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/svelte'
  import TreeNode from './TreeNode.svelte'
  import { createFileTreeCollection, defaultExpandedBranches } from '../data'
  import '../style.css'

  const controls = useControls(treeControls)
  const id = $props.id()
  const collection = createFileTreeCollection()

  const controlContext = $derived({
    dir: controls.context.dir,
    selectionMode: controls.context.selectionMode,
    expandOnClick: controls.context.openOnClick,
  })

  const [snapshot, send] = useMachine(
    tree.machine({
      id,
      collection,
      defaultExpandedValue: defaultExpandedBranches,
    }),
    {
      context: controlContext,
    },
  )

  const api = $derived(tree.connect(snapshot, send, normalizeProps))
</script>

<Layout>
  <main class="tree-example">
    <section class="tree-example__card">
      <div class="tree-example__header">
        <h3 {...api.getLabelProps()}>Project files</h3>
        <span class="tree-example__meta">{api.expandedValue.length} open folders</span>
      </div>

      <div class="tree-example__actions">
        <button type="button" onclick={() => api.expand()}>Expand all</button>
        <button type="button" onclick={() => api.collapse()}>Collapse all</button>
        <button type="button" onclick={() => api.select()}>Select all</button>
        <button type="button" onclick={() => api.deselect()}>Clear selection</button>
      </div>

      <div {...api.getRootProps()}>
        <div {...api.getTreeProps()}>
          {#each api.collection.rootNode.children ?? [] as node, index}
            <TreeNode {node} indexPath={[index]} api={api} />
          {/each}
        </div>
      </div>
    </section>
  </main>

  <Toolbar {controls}>
    <StateVisualizer state={snapshot} omit={['collection']} />
  </Toolbar>
</Layout>
