// examples/svelte/src/components/TreeNode.svelte
<script lang="ts">
  import type { Api } from "@destyler/tree"

  const {node,indexPath, api} = $props()

  const nodeProps = $derived({
    indexPath,
    node,
  })

  const nodeState = $derived(api.getNodeState(nodeProps))
</script>

{#if nodeState.isBranch}
  <div {...api.getBranchProps(nodeProps)}>
    <div {...api.getBranchControlProps(nodeProps)}>
      <span {...api.getBranchTextProps(nodeProps)}>{node.name}</span>
      <span {...api.getBranchIndicatorProps(nodeProps)}></span>
    </div>
    <div {...api.getBranchContentProps(nodeProps)}>
      <div {...api.getBranchIndentGuideProps(nodeProps)} ></div>
      {#each node.children || [] as childNode, index (childNode.id)}
        <svelte:self
          node={childNode}
          indexPath={[...indexPath, index]}
          {api}
        ></svelte:self>
      {/each}
    </div>
  </div>
{:else}
  <div {...api.getItemProps(nodeProps)}>{node.name}</div>
{/if}

// examples/solid/src/components/TreeNode.tsx
import type { Api } from '@destyler/tree'
import { createMemo, For } from 'solid-js'

interface Node {
  id: string
  name: string
  children?: Node[]
}

interface Props {
  node: Node
  indexPath: number[]
  api: Api
}

export function TreeNode(props: Props) {
  const nodeProps = createMemo(() => ({
    indexPath: props.indexPath,
    node: props.node,
  }))

  const nodeState = createMemo(() => props.api.getNodeState(nodeProps()))

  return (
    <>
      {createMemo(() => nodeState().isBranch)()
        ? (
            <div {...props.api.getBranchProps(nodeProps())}>
              <div {...props.api.getBranchControlProps(nodeProps())}>
                <span {...props.api.getBranchTextProps(nodeProps())}>{props.node.name}</span>
                <span {...props.api.getBranchIndicatorProps(nodeProps())} />
              </div>
              <div {...props.api.getBranchContentProps(nodeProps())}>
                <div {...props.api.getBranchIndentGuideProps(nodeProps())} />
                <For each={props.node.children}>
                  {(childNode, index) => (
                    <TreeNode
                      node={childNode}
                      indexPath={[...props.indexPath, index()]}
                      api={props.api}
                    />
                  )}
                </For>
              </div>
            </div>
          )
        : (
            <div {...props.api.getItemProps(nodeProps())}>{props.node.name}</div>
          )}
    </>
  )
}
