// packages/components/collapsible/snippets/Collapsible.vue
<script setup lang="ts">
import * as collapsible from '@destyler/collapsible'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'
import './style.css'

const [state, send] = useMachine(collapsible.machine({ id: useId() }))

const api = computed(() =>
  collapsible.connect(state.value, send, normalizeProps),
)
</script>

<template>
  <div v-bind="api.getRootProps()">
    <div>
      <h4>@elonehoo starred 3 repositories</h4>
      <button v-bind="api.getTriggerProps()">
        <div />
      </button>
    </div>

    <div>@destyler/collapsible</div>

    <div v-bind="api.getContentProps()">
      <div>@destyler/vue</div>
      <div>vue</div>
    </div>
  </div>
</template>

// packages/components/collapsible/snippets/Collapsible.react.tsx
import * as collapsible from '@destyler/collapsible'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'
import './style.css'

export default function Collapsible() {
  const [state, send] = useMachine(collapsible.machine({ id: useId() }))
  const api = collapsible.connect(state, send, normalizeProps)

  return (
    <div {...api.getRootProps()}>
      <div>
        <h4>@elonehoo starred 3 repositories</h4>
        <button {...api.getTriggerProps()}>
          <div />
        </button>
      </div>

      <div>@destyler/collapsible</div>

      <div {...api.getContentProps()}>
        <div>@destyler/react</div>
        <div>react</div>
      </div>
    </div>
  )
}
