// examples/vue/src/pages/carousel.vue
<script setup lang="ts">
import * as carousel from '@destyler/carousel'
import { carouselControls } from '@destyler/shared-private'
import { Controls, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/vue'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'

const controls = useControls(carouselControls)

const items = [
  'https://elonehoo.me/coffee/01.jpeg',
  'https://elonehoo.me/coffee/02.jpeg',
]

const [state, send] = useMachine(
  carousel.machine({
    id: useId(),
    slideCount: items.length,
    spacing: '20px',
    slidesPerPage: 1,
    autoplay: false,
  }),
  {
    context: controls.context,
  },
)

const api = computed(() =>
  carousel.connect(state.value, send, normalizeProps),
)
</script>

<template>
  <div
    v-bind="api.getRootProps()"
    class="flex items-center justify-center flex-col gap-4 w-100 relative"
  >
    <div v-bind="api.getItemGroupProps()" class="rounded-xl">
      <div
        v-for="(image, index) in items"
        :key="index"
        v-bind="api.getItemProps({ index })"
      >
        <img :src="image" alt="">
      </div>
    </div>
    <button @click="api.scrollToIndex(1)">
      Scroll to 1
    </button>
    <!-- control -->
    <div
      v-bind="api.getControlProps()"
      class="absolute bottom-4 left-1/2 -translate-x-1/2 flex justify-center items-center bg-dark rounded-md px-2 py-1"
    >
      <button v-bind="api.getAutoplayTriggerProps()">
        {{ api.isPlaying ? 'Stop' : 'Play' }}
      </button>
      <button
        v-bind="api.getPrevTriggerProps()"
        class="w-4 h-4 text-light i-carbon:caret-left"
      />
      <div v-bind="api.getIndicatorGroupProps()" class="flex gap-2 mx-2">
        <button
          v-for="(_, index) in api.pageSnapPoints"
          :key="index"
          v-bind="api.getIndicatorProps({ index })"
          class="w-2 h-2 bg-gray rounded-full data-[current]:bg-green"
        />
      </div>
      <button
        v-bind="api.getNextTriggerProps()"
        class="w-4 h-4 text-light i-carbon:caret-right"
      />
    </div>
  </div>
  <Toolbar>
    <StateVisualizer :state="state" />
    <template #controls>
      <Controls :control="controls" />
    </template>
  </Toolbar>
</template>

// examples/svelte/src/pages/carousel.svelte
<script lang="ts">
  import * as carousel from '@destyler/carousel'
  import { carouselControls } from '@destyler/shared-private'
  import { normalizeProps, useMachine } from '@destyler/svelte'
  import {useControls, Toolbar, StateVisualizer} from '@destyler/shared-private/svelte'

  const controls = useControls(carouselControls)

  const items = [
    'https://elonehoo.me/coffee/01.jpeg',
    'https://elonehoo.me/coffee/02.jpeg',
  ]

  const uid = $props.id();

  const [state, send] = useMachine(
    carousel.machine({
      id: uid,
      slideCount: items.length,
      spacing: '20px',
      slidesPerPage: 1,
      autoplay: false,
    }),
    {
      context: controls.context,
    },
  )

  const api = $derived(carousel.connect(state, send, normalizeProps))
</script>

<div
  {...api.getRootProps()}
  class="flex items-center justify-center flex-col gap-4 w-100 relative"
>
  <div {...api.getItemGroupProps()} class="rounded-xl">
    {#each items as image, index}
      <div {...api.getItemProps({ index })}>
        <img src={image} alt="" />
      </div>
    {/each}
  </div>

  <!-- control -->
  <button onclick={() => api.scrollToIndex(1)}>Scroll to 1</button>
  <div
    {...api.getControlProps()}
    class="absolute bottom-4 left-1/2 -translate-x-1/2 flex justify-center items-center bg-dark rounded-md px-2 py-1"
  >
    <button {...api.getAutoplayTriggerProps()}>{api.isPlaying ? 'Stop' : 'Play'}</button>
    <button
      {...api.getPrevTriggerProps()}
      class="w-4 h-4 text-light i-carbon:caret-left"
    >
    </button>
    <div {...api.getIndicatorGroupProps()} class="flex gap-2 mx-2">
      {#each api.pageSnapPoints as _, index}
        <button
          {...api.getIndicatorProps({ index })}
          class="w-2 h-2 bg-gray rounded-full data-[current]:bg-green"
        >
        </button>
      {/each}
    </div>
    <button
      {...api.getNextTriggerProps()}
      class="w-4 h-4 text-light i-carbon:caret-right"
    >
    </button>
  </div>
</div>

<Toolbar {controls}>
  <StateVisualizer state={state} />
</Toolbar>
