// examples/react/src/pages/toast.tsx
import { normalizeProps, Portal, useMachine } from '@destyler/react'
import * as toast from '@destyler/toast'
import { useId } from 'react'
import { ToastItem } from '../components/ToastItem'
import '@destyler/shared-private/styles/toast.css'

export default function Toast() {
  const [state, send] = useMachine(
    toast.group.machine({
      id: useId(),
      placement: 'bottom-end',
      overlap: true,
      removeDelay: 200,
    }),
  )

  const api = toast.group.connect(state as any, send, normalizeProps)

  return (
    <div>
      <button
        className="create-trigger"
        onClick={() => {
          api.create({
            title: 'Fetching data...',
            type: 'info',
          })
        }}
      >
        Notify
      </button>

      <Portal>
        {api.getPlacements().map(placement => (
          <div key={placement} {...api.getGroupProps({ placement })}>
            {api.getToastsByPlacement(placement).map(toast => (
              <ToastItem key={toast.id} actor={toast} />
            ))}
          </div>
        ))}
      </Portal>
    </div>
  )
}

// examples/svelte/src/pages/toast.svelte
<script lang="ts">
  import * as toast from '@destyler/toast'
  import {normalizeProps, useMachine, portal} from '@destyler/svelte'
  import '@destyler/shared-private/styles/toast.css'
  import ToastItem from '../components/ToastItem.svelte';

  const id = $props.id()

  const [state, send] = useMachine(
    toast.group.machine({
      id: id,
      placement: 'bottom-end',
      overlap: true,
      removeDelay: 200,
    }),
  )

  const api = $derived(toast.group.connect(state as any, send, normalizeProps))
</script>

<button
  class="create-trigger"
  onclick={() => {
    api.create({
      title: "Fetching data...",
      type: "info",
    })
  }}
>
  Notify
</button>

<div use:portal>
  {#each api.getPlacements() as placement}
    <div {...api.getGroupProps({ placement })}>
      {#each api.getToastsByPlacement(placement) as toast (toast.id)}
        <ToastItem actor={toast} />
      {/each}
    </div>
  {/each}
</div>
