// packages/components/checkbox/examples/react/Checkbox.react.tsx
import { normalizeProps, useMachine } from '@destyler/react'
import { checkboxControls } from '@destyler/shared-private'
import { Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/react'
import { useId } from 'react'
import * as checkbox from '../../index'
import '../style.css'

export default function Checkbox() {
  const controls = useControls(checkboxControls)

  const [state, send] = useMachine(checkbox.machine({
    id: useId(),
  }), {
    context: controls.context,
  })

  const api = checkbox.connect(state, send, normalizeProps)

  return (
    <Layout>
      <main>main</main>
      <label {...api.getRootProps()}>
        <div {...api.getControlProps()} />
        <span {...api.getLabelProps()}>
          Input is
          { api.checked ? ' checked' : ' unchecked' }
        </span>

        <input data-testid="hidden-input" {...api.getHiddenInputProps()} />
      </label>
      <Toolbar controls={controls.ui()}>
        <StateVisualizer state={state} />
      </Toolbar>
    </Layout>
  )
}

// packages/components/checkbox/examples/vue/Checkbox.vue
<script setup lang="ts">
import { checkboxControls } from '@destyler/shared-private'
import { Controls, Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/vue'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'
import * as checkbox from '../../index'
import '../style.css'

const controls = useControls(checkboxControls)

const [state, send] = useMachine(checkbox.machine({ id: useId() }), {
  context: controls.context,
})

const api = computed(() =>
  checkbox.connect(state.value, send, normalizeProps),
)
</script>

<template>
  <Layout>
    <main>main</main>
    <label v-bind="api.getRootProps()">
      <div v-bind="api.getControlProps()" />
      <span v-bind="api.getLabelProps()">
        Input is
        <span v-if="api.checked"> checked</span>
        <span v-else> unchecked</span>
      </span>

      <input data-testid="hidden-input" v-bind="api.getHiddenInputProps()">
    </label>

    <Toolbar>
      <StateVisualizer :state="state" />
      <template #controls>
        <Controls :control="controls" />
      </template>
    </Toolbar>
  </Layout>
</template>
