// packages/components/tree/examples/svelte/TreeNode.svelte
<script lang="ts">
  import type { FileNode } from '../data'
  import type { Api } from '../../index'

  export let node: FileNode
  export let indexPath: number[]
  export let api: Api

  $: nodeProps = { node, indexPath }
  $: nodeState = api.getNodeState(nodeProps)
  $: childCount = node.children?.length ?? 0
</script>

{#if nodeState.isBranch}
  <div {...api.getBranchProps(nodeProps)}>
    <div {...api.getBranchControlProps(nodeProps)}>
      <span {...api.getBranchIndicatorProps(nodeProps)}></span>
      <span {...api.getBranchTextProps(nodeProps)}>{node.name}</span>
      <span class="tree-example__meta">{childCount} items</span>
    </div>
    {#if nodeState.expanded}
      <div {...api.getBranchContentProps(nodeProps)}>
        <div {...api.getBranchIndentGuideProps(nodeProps)}></div>
        {#each node.children ?? [] as child, index}
          <svelte:self node={child} indexPath={[...indexPath, index]} {api} />
        {/each}
      </div>
    {/if}
  </div>
{:else}
  <div {...api.getItemProps(nodeProps)}>
    <span {...api.getItemIndicatorProps(nodeProps)}></span>
    <span {...api.getItemTextProps(nodeProps)}>{node.name}</span>
  </div>
{/if}

// packages/components/tree/examples/react/TreeNode.react.tsx
import type { FileNode } from '../data'
import type { Api } from '../../index'
import { useMemo } from 'react'

interface TreeNodeProps {
  node: FileNode
  indexPath: number[]
  api: Api
}

export default function TreeNode({ node, indexPath, api }: TreeNodeProps) {
  const nodeProps = useMemo(() => ({ node, indexPath }), [node, indexPath])
  const nodeState = api.getNodeState(nodeProps)

  if (nodeState.isBranch) {
    const childCount = node.children?.length ?? 0
    return (
      <div {...api.getBranchProps(nodeProps)}>
        <div {...api.getBranchControlProps(nodeProps)}>
          <span {...api.getBranchIndicatorProps(nodeProps)} />
          <span {...api.getBranchTextProps(nodeProps)}>{node.name}</span>
          <span className="tree-example__meta">{childCount} items</span>
        </div>
        {nodeState.expanded && (
          <div {...api.getBranchContentProps(nodeProps)}>
            <div {...api.getBranchIndentGuideProps(nodeProps)} />
            {node.children?.map((childNode, childIndex) => (
              <TreeNode
                key={childNode.id}
                node={childNode}
                indexPath={[...indexPath, childIndex]}
                api={api}
              />
            ))}
          </div>
        )}
      </div>
    )
  }

  return (
    <div {...api.getItemProps(nodeProps)}>
      <span {...api.getItemIndicatorProps(nodeProps)} />
      <span {...api.getItemTextProps(nodeProps)}>{node.name}</span>
    </div>
  )
}
