// packages/components/collapse/examples/solid/Collapse.solid.tsx
/** @jsxImportSource solid-js */
import { collapseControls, collapseData } from '@destyler/shared-private'
import { Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/solid'
import { normalizeProps, useMachine } from '@destyler/solid'
import { createMemo, createUniqueId } from 'solid-js'
import { For } from 'solid-js/web'
import * as collapse from '../../index'
import '../style.css'

export default function Collapse() {
  const controls = useControls(collapseControls)

  const [state, send] = useMachine(collapse.machine({
    id: createUniqueId(),
  }), {
    context: controls.context,
  })

  const api = createMemo(() => collapse.connect(state, send, normalizeProps))

  return (
    <Layout>
      <main>
        <div {...api().getRootProps()}>
          <For each={collapseData}>
            {item => (
              <div {...api().getItemProps({ value: item.id })}>
                <h3>
                  <button data-testid={`${item.id}:trigger`} {...api().getItemTriggerProps({ value: item.id })}>
                    {item.title}
                    <div {...api().getItemIndicatorProps({ value: item.id })}>
                      &gt;
                    </div>
                  </button>
                </h3>
                <div {...api().getItemContentProps({ value: item.id })} data-testid={`${item.id}:content`}>
                  {item.content}
                </div>
              </div>
            )}
          </For>
        </div>
      </main>
      <Toolbar controls={controls.ui}>
        <StateVisualizer state={state} />
      </Toolbar>
    </Layout>
  )
}

// packages/components/collapse/examples/svelte/Collapse.svelte
<script lang="ts">
import { collapseControls, collapseData } from '@destyler/shared-private'
import { useControls, Toolbar, StateVisualizer, Layout } from '@destyler/shared-private/svelte'
import { normalizeProps, useMachine } from '@destyler/svelte'
import * as collapse from '../../index'
import '../style.css'

const controls = useControls(collapseControls)

const id = $props.id();

const [state, send] = useMachine(collapse.machine({
  id,
}), {
  context: controls.context,
})

const api = $derived(collapse.connect(state, send, normalizeProps))
</script>

<Layout>
  <main>
    <div {...api.getRootProps()}>
      {#each collapseData as item (item.id)}
        <div {...api.getItemProps({ value: item.id })}>
          <h3>
            <button data-testid="{item.id}:trigger" {...api.getItemTriggerProps({ value: item.id })}>
              {item.title}
              <div {...api.getItemIndicatorProps({ value: item.id })}>
                &gt;
              </div>
            </button>
          </h3>
          <div {...api.getItemContentProps({ value: item.id })} data-testid="{item.id}:content">
            {item.content}
          </div>
        </div>
      {/each}
    </div>
  </main>
  <Toolbar {controls}>
    <StateVisualizer state={state} />
  </Toolbar>
</Layout>
