// packages/components/toggle/examples/svelte/Toggle.svelte
<script lang="ts">
  import { toggleControls, toggleData } from "@destyler/shared-private"
  import { normalizeProps, useMachine } from "@destyler/svelte"
  import {useControls, Toolbar, StateVisualizer, Layout} from '@destyler/shared-private/svelte'
  import * as toggle from "../../index"
  import '../style.css'

  const controls = useControls(toggleControls)

  const [snapshot, send] = useMachine(toggle.machine({ id: "1" }), {
    context: controls.context,
  })

  const api = $derived(toggle.connect(snapshot, send, normalizeProps))
</script>

<Layout>
  <main class="toggle-group">
    <button>Outside</button>
    <div {...api.getRootProps()}>
      {#each toggleData as item}
        <button {...api.getItemProps({ value: item.value })}>
          {item.label}
        </button>
      {/each}
    </div>
  </main>

  <Toolbar {controls}>
    <StateVisualizer state={snapshot} />
  </Toolbar>
</Layout>

// packages/components/toggle/examples/solid/Toggle.solid.tsx
/** @jsxImportSource solid-js */

import { toggleControls, toggleData } from '@destyler/shared-private'
import { Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/solid'
import { normalizeProps, useMachine } from '@destyler/solid'
import { createMemo, createUniqueId, For } from 'solid-js'
import * as toggle from '../../index'
import '../style.css'

export default function Page() {
  const controls = useControls(toggleControls)

  const [state, send] = useMachine(toggle.machine({ id: createUniqueId() }), {
    context: controls.context,
  })

  const api = createMemo(() => toggle.connect(state, send, normalizeProps))

  return (
    <Layout>
      <main class="toggle-group">
        <button>Outside</button>
        <div {...api().getRootProps()}>
          <For each={toggleData}>
            {item => <button {...api().getItemProps({ value: item.value })}>{item.label}</button>}
          </For>
        </div>
      </main>

      <Toolbar controls={controls.ui} viz>
        <StateVisualizer state={state} />
      </Toolbar>
    </Layout>
  )
}
