// packages/components/toggle/docs/snippets/toggleGroup/ToggleGroup.vue
<script setup lang="ts">
import * as toggle from '@destyler/toggle'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'
import '@docs/styles/components/toggle.css'

const [state, send] = useMachine(toggle.machine({
  id: useId(),
  multiple: true,
  value: ['bold'],
}))
const api = computed(() => toggle.connect(state.value, send, normalizeProps))
</script>

<template>
  <div class="flex items-center justify-center mt-0!">
    <div
      v-bind="api.getRootProps()"
    >
      <button
        v-for="(item, index) in ['bold', 'italic', 'underline']"
        :key="index"
        v-bind="api.getItemProps({ value: item })"
      >
        {{ item[0].toUpperCase() }}
      </button>
    </div>
  </div>
</template>

// packages/components/toggle/docs/snippets/toggleGroup/ToggleGroup.react.tsx
import { normalizeProps, useMachine } from '@destyler/react'
import * as toggle from '@destyler/toggle'
import { useId } from 'react'
import '@docs/styles/components/toggle.css'

export default function TogglePage() {
  const [state, send] = useMachine(toggle.machine({
    id: useId(),
    multiple: true,
    value: ['bold'],
  }))

  const api = toggle.connect(state, send, normalizeProps)

  return (
    <div className="flex items-center justify-center mt-0!">
      <div {...api.getRootProps()}>
        {['bold', 'italic', 'underline'].map(item => (
          <button key={item} {...api.getItemProps({ value: item })}>
            {item[0].toUpperCase()}
          </button>
        ))}
      </div>
    </div>
  )
}
