// packages/components/toggle/snippets/Toggle.vue
<script setup lang="ts">
import * as toggle from '@destyler/toggle'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'
import './style.css'

const [state, send] = useMachine(toggle.machine({
  id: useId(),
  multiple: true,
  defaultValue: ['bold'],
}))
const api = computed(() => toggle.connect(state.value, send, normalizeProps))
</script>

<template>
  <div class="flex items-center justify-center mt-0!">
    <div
      v-bind="api.getRootProps()"
    >
      <button
        v-for="(item, index) in ['bold', 'italic', 'underline']"
        :key="index"
        v-bind="api.getItemProps({ value: item })"
      >
        {{ item[0].toUpperCase() }}
      </button>
    </div>
  </div>
</template>

// packages/components/toggle/snippets/Toggle.svelte
<script lang="ts">
  import * as toggle from "@destyler/toggle";
  import { normalizeProps, useMachine } from "@destyler/svelte";
  import './style.css'

  const id = $props.id();
  const [state, send] = useMachine(toggle.machine({
    id,
    multiple: true,
    defaultValue: ['bold'],
  }));

  const api = $derived(toggle.connect(state, send, normalizeProps));
</script>

<div class="flex items-center justify-center mt-0!">
  <div {...api.getRootProps()}>
    {#each ['bold', 'italic', 'underline'] as item, index (index)}
      <button {...api.getItemProps({ value: item })}>
        {item[0].toUpperCase()}
      </button>
    {/each}
  </div>
</div>
