// packages/components/timer/snippets/Timer.react.tsx
import { normalizeProps, useMachine } from '@destyler/react'
import * as timer from '@destyler/timer'
import { useId } from 'react'
import './style.css'

export default function Timer() {
  const [state, send] = useMachine(
    timer.machine({
      id: useId(),
      countdown: true,
      autoStart: true,
      startMs: timer.parse({ days: 20, seconds: 1 }),
    }),
  )

  const api = timer.connect(state, send, normalizeProps)

  return (
    <>
      <div {...api.getRootProps()}>
        <div {...api.getAreaProps()}>
          <div {...api.getItemProps({ type: 'days' })}>
            {api.formattedTime.days}
          </div>
          <div {...api.getSeparatorProps()}>
            :
          </div>
          <div {...api.getItemProps({ type: 'hours' })}>
            {api.formattedTime.hours}
          </div>
          <div {...api.getSeparatorProps()}>
            :
          </div>
          <div {...api.getItemProps({ type: 'minutes' })}>
            {api.formattedTime.minutes}
          </div>
          <div {...api.getSeparatorProps()}>
            :
          </div>
          <div {...api.getItemProps({ type: 'seconds' })}>
            {api.formattedTime.seconds}
          </div>
        </div>
      </div>
    </>
  )
}

// packages/components/timer/snippets/Timer.vue
<script setup lang="ts">
import * as timer from '@destyler/timer'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'
import './style.css'

const [state, send] = useMachine(
  timer.machine({
    id: useId(),
    countdown: true,
    autoStart: true,
    startMs: timer.parse({ days: 20, seconds: 1 }),
  }),
)

const api = computed(() => timer.connect(state.value, send, normalizeProps))
</script>

<template>
  <div v-bind="api.getRootProps()">
    <div v-bind="api.getAreaProps()">
      <div v-bind="api.getItemProps({ type: 'days' })">
        {{ api.formattedTime.days }}
      </div>
      <div v-bind="api.getSeparatorProps()">
        :
      </div>
      <div v-bind="api.getItemProps({ type: 'hours' })">
        {{ api.formattedTime.hours }}
      </div>
      <div v-bind="api.getSeparatorProps()">
        :
      </div>
      <div v-bind="api.getItemProps({ type: 'minutes' })">
        {{ api.formattedTime.minutes }}
      </div>
      <div v-bind="api.getSeparatorProps()">
        :
      </div>
      <div v-bind="api.getItemProps({ type: 'seconds' })">
        {{ api.formattedTime.seconds }}
      </div>
    </div>
  </div>
</template>
