// packages/components/dynamic/examples/svelte/Dynamic.svelte
<script lang="ts">
  import * as dynamic from "../../index";
  import { normalizeProps, useMachine } from "@destyler/svelte";
  import { dynamicControls } from '@destyler/shared-private';
  import {useControls, Toolbar, StateVisualizer, Layout} from '@destyler/shared-private/svelte'
  import '../style.css'

  const controls = useControls(dynamicControls);

  const [state, send] = useMachine(
    dynamic.machine({
      id: crypto.randomUUID(),
      value: ["React", "Vue"],
    }),
    {
      context: controls.context,
    }
  );

  const api = $derived(dynamic.connect(state, send, normalizeProps));
</script>

<Layout>
  <main>
    <input data-testid="copy-text" style="margin-bottom: 1rem;" />
    <div {...api.getRootProps()}>
      <div>
        {#each api.value as value, index (index)}
          <span {...api.getItemProps({ index, value })} style="position: relative;">
            <div
              data-testid={`${value.toLowerCase()}-input`}
              {...api.getItemPreviewProps({ index, value })}
            >
              <span>{value}</span>
              <button
                {...api.getItemDeleteTriggerProps({ index, value })}
                data-testid={`${value.toLowerCase()}-delete-trigger`}
              >
                &#x2715;
              </button>
            </div>
            <input
              {...api.getItemInputProps({ index, value })}
              data-testid={`${value.toLowerCase()}-item-input`}
            />
          </span>
        {/each}
      </div>
      <input
        placeholder="Add tag..."
        {...api.getInputProps()}
      />
    </div>
  </main>

  <Toolbar {controls}>
    <StateVisualizer state={state} />
  </Toolbar>
</Layout>

// packages/components/dynamic/examples/vue/Dynamic.vue
<script setup lang="ts">
import { dynamicControls } from '@destyler/shared-private'
import { Controls, Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/vue'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'
import * as dynamic from '../../index'
import '../style.css'

const controls = useControls(dynamicControls)

function toDashCase(str: string) {
  return str.replace(/\s+/g, '-').toLowerCase()
}

const [state, send] = useMachine(
  dynamic.machine({
    id: useId(),
    value: ['React', 'Vue'],
  }),
  { context: controls.context },
)

const api = computed(() => dynamic.connect(state.value, send, normalizeProps))
</script>

<template>
  <Layout>
    <main>
      <input data-testid="copy-text" style="margin-bottom: 1rem;">
      <div v-bind="api.getRootProps()">
        <div>
          <span
            v-for="(value, index) in api.value"
            :key="index"
            v-bind="api.getItemProps({ index, value })"
            style="position: relative;"
          >
            <div
              :data-testid="`${toDashCase(value)}-input`"
              v-bind="api.getItemPreviewProps({ index, value })"
            >
              <span>{{ value }}</span>
              <button
                v-bind="api.getItemDeleteTriggerProps({ index, value })"
                :data-testid="`${toDashCase(value)}-delete-trigger`"
              >
                &#x2715;
              </button>
            </div>
            <input
              v-bind="api.getItemInputProps({ index, value })"
              :data-testid="`${toDashCase(value)}-item-input`"
            >
          </span>
        </div>
        <input
          placeholder="Add tag..."
          v-bind="api.getInputProps()"
        >
      </div>
    </main>

    <Toolbar>
      <StateVisualizer :state="state" />
      <template #controls>
        <Controls :control="controls" />
      </template>
    </Toolbar>
  </Layout>
</template>
