// packages/components/number-input/docs/snippets/number-input/NumberInput.svelte
<script lang="ts">
  import * as numberInput from '@destyler/number-input'
  import { normalizeProps, useMachine } from '@destyler/svelte'
  import '@docs/styles/components/number-input.css'

  const id = $props.id()

  const [state, send] = useMachine(numberInput.machine({
    id,
    value: '66',
    allowMouseWheel: true,
  }))

  const api = $derived(numberInput.connect(state, send, normalizeProps))
</script>

<div {...api.getRootProps()}>
  <button {...api.getDecrementTriggerProps()}>
    <span>-</span>
  </button>
  <input {...api.getInputProps()}/>
  <button {...api.getIncrementTriggerProps()}>
    <span>+</span>
  </button>
</div>

// packages/components/number-input/docs/snippets/number-input/NumberInput.react.tsx
import * as numberInput from '@destyler/number-input'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'
import '@docs/styles/components/number-input.css'

export default function NumberInput() {
  const [state, send] = useMachine(numberInput.machine({
    id: useId(),
    value: '66',
    allowMouseWheel: true,
  }))

  const api = numberInput.connect(state, send, normalizeProps)

  return (
    <div {...api.getRootProps()}>
      <button {...api.getDecrementTriggerProps()}>
        <span>-</span>
      </button>
      <input {...api.getInputProps()} />
      <button {...api.getIncrementTriggerProps()}>
        <span>+</span>
      </button>
    </div>
  )
}
