// packages/components/progress/snippets/Progress.vue
<script setup lang="ts">
import * as progress from '@destyler/progress'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'
import './style.css'

const [state, send] = useMachine(progress.machine({ id: useId(), value: 30 }))

const api = computed(() =>
  progress.connect(state.value, send, normalizeProps),
)
</script>

<template>
  <div v-bind="api.getRootProps()">
    <div v-bind="api.getTrackProps()">
      <div v-bind="api.getRangeProps()" />
    </div>
  </div>
</template>

// packages/components/progress/snippets/Progress.react.tsx
import * as progress from '@destyler/progress'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'
import './style.css'

export default function Progress({ className = '' }: { className?: string }) {
  const [state, send] = useMachine(progress.machine({
    id: useId(),
    value: 30,
  }))

  const api = progress.connect(state, send, normalizeProps)

  return (
    <div {...api.getRootProps()} className={`${className}`}>
      <div {...api.getTrackProps()}>
        <div {...api.getRangeProps()} />
      </div>
    </div>
  )
}
