// examples/vue/src/pages/calendar.vue
<script setup lang="ts">
import * as calendar from '@destyler/calendar'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'

const [state, send] = useMachine(
  calendar.machine({
    id: useId(),
  }),
)
const api = computed(() =>
  calendar.connect(state.value, send, normalizeProps),
)
</script>

<template>
  <div v-bind="api.getControlProps()">
    <input v-bind="api.getInputProps()">
    <button v-bind="api.getTriggerProps()">
      🗓
    </button>
  </div>
  <Teleport to="body">
    <div v-bind="api.getPositionerProps()">
      <div v-bind="api.getContentProps()">
        <!-- Day View -->
        <div v-show="api.view !== 'day'">
          <div v-bind="api.getViewControlProps({ view: 'year' })">
            <button v-bind="api.getPrevTriggerProps()">
              Prev
            </button>
            <button v-bind="api.getViewTriggerProps()">
              {{ api.visibleRangeText.start }}
            </button>
            <button v-bind="api.getNextTriggerProps()">
              Next
            </button>
          </div>

          <table v-bind="api.getTableProps({ view: 'day' })">
            <thead v-bind="api.getTableHeaderProps({ view: 'day' })">
              <tr v-bind="api.getTableRowProps({ view: 'day' })">
                <template v-for="(day, index) in api.weekDays" :key="index">
                  <th scope="col">
                    {{ day.narrow }}
                  </th>
                </template>
              </tr>
            </thead>
            <tbody v-bind="api.getTableBodyProps({ view: 'day' })">
              <template v-for="(week, weekIndex) in api.weeks" :key="weekIndex">
                <tr v-bind="api.getTableRowProps({ view: 'day' })">
                  <template v-for="(value, weekValueKey) in week" :key="weekValueKey">
                    <td v-bind="api.getDayTableCellProps({ value })">
                      <div v-bind="api.getDayTableCellTriggerProps({ value })">
                        {{ value.day }}
                      </div>
                    </td>
                  </template>
                </tr>
              </template>
            </tbody>
          </table>
        </div>

        <!-- Month View -->
        <div v-show="api.view !== 'month'">
          <div v-bind="api.getViewControlProps({ view: 'month' })">
            <button v-bind="api.getPrevTriggerProps({ view: 'month' })">
              Prev
            </button>
            <button v-bind="api.getViewTriggerProps({ view: 'month' })">
              {{ api.visibleRange.start.year }}
            </button>
            <button v-bind="api.getNextTriggerProps({ view: 'month' })">
              Next
            </button>
          </div>

          <table v-bind="api.getTableProps({ view: 'month', columns: 4 })">
            <tbody v-bind="api.getTableBodyProps({ view: 'month' })">
              <template v-for="(months, key) in api.getMonthsGrid({ columns: 4, format: 'short' })" :key="key">
                <tr v-bind="api.getTableRowProps()">
                  <template v-for="(month, index) in months" :key="index">
                    <td
                      v-bind="api.getMonthTableCellProps({
                        ...month,
                        columns: 4,
                      })"
                    >
                      <div
                        v-bind="api.getMonthTableCellTriggerProps({
                          ...month,
                          columns: 4,
                        })"
                      >
                        {{ month.label }}
                      </div>
                    </td>
                  </template>
                </tr>
              </template>
            </tbody>
          </table>
        </div>

        <!-- Year View -->
        <div v-show="api.view !== 'year'">
          <div v-bind="api.getViewControlProps({ view: 'year' })">
            <button v-bind="api.getPrevTriggerProps({ view: 'year' })">
              Prev
            </button>
            <span>
              {{ api.getDecade().start }} - {{ api.getDecade().end }}
            </span>
            <button v-bind="api.getNextTriggerProps({ view: 'year' })">
              Next
            </button>
          </div>

          <table v-bind="api.getTableProps({ view: 'year', columns: 4 })">
            <tbody v-bind="api.getTableBodyProps()">
              <template v-for="(years, key) in api.getYearsGrid({ columns: 4 })" :key="key">
                <tr v-bind="api.getTableRowProps({ view: 'year' })">
                  <template v-for="(year, index) in years" :key="index">
                    <td
                      v-bind="api.getYearTableCellProps({
                        ...year,
                        columns: 4,
                      })"
                    >
                      <div
                        v-bind="api.getYearTableCellTriggerProps({
                          ...year,
                          columns: 4,
                        })"
                      >
                        {{ year.label }}
                      </div>
                    </td>
                  </template>
                </tr>
              </template>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </Teleport>
</template>

// examples/react/src/pages/calendar.tsx
import * as calendar from '@destyler/calendar'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'
import { createPortal } from 'react-dom'

export default function Calendar() {
  const [state, send] = useMachine(
    calendar.machine({
      id: useId(),
    }),
  )

  const api = calendar.connect(state, send, normalizeProps)

  return (
    <>
      <div {...api.getControlProps()}>
        <input {...api.getInputProps()} />
        <button {...api.getTriggerProps()}>
          🗓
        </button>
      </div>
      {createPortal(
        <div {...api.getPositionerProps()}>
          <div {...api.getContentProps()}>
            {/* Day View */}
            {api.view !== 'day' && (
              <div>
                <div {...api.getViewControlProps({ view: 'year' })}>
                  <button {...api.getPrevTriggerProps()}>
                    Prev
                  </button>
                  <button {...api.getViewTriggerProps()}>
                    {api.visibleRangeText.start}
                  </button>
                  <button {...api.getNextTriggerProps()}>
                    Next
                  </button>
                </div>

                <table {...api.getTableProps({ view: 'day' })}>
                  <thead {...api.getTableHeaderProps({ view: 'day' })}>
                    <tr {...api.getTableRowProps({ view: 'day' })}>
                      {api.weekDays.map(day => (
                        <th key={day.narrow} scope="col">
                          {day.narrow}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody {...api.getTableBodyProps({ view: 'day' })}>
                    {api.weeks.map((week, weekIndex) => (
                      <tr key={weekIndex} {...api.getTableRowProps({ view: 'day' })}>
                        {week.map(value => (
                          <td key={value.day} {...api.getDayTableCellProps({ value })}>
                            <div {...api.getDayTableCellTriggerProps({ value })}>
                              {value.day}
                            </div>
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {/* Month View */}
            {api.view !== 'month' && (
              <div>
                <div {...api.getViewControlProps({ view: 'month' })}>
                  <button {...api.getPrevTriggerProps({ view: 'month' })}>
                    Prev
                  </button>
                  <button {...api.getViewTriggerProps({ view: 'month' })}>
                    {api.visibleRange.start.year}
                  </button>
                  <button {...api.getNextTriggerProps({ view: 'month' })}>
                    Next
                  </button>
                </div>

                <table {...api.getTableProps({ view: 'month', columns: 4 })}>
                  <tbody {...api.getTableBodyProps({ view: 'month' })}>
                    {api.getMonthsGrid({ columns: 4, format: 'short' }).map((months, monthIndex) => (
                      <tr key={monthIndex} {...api.getTableRowProps()}>
                        {months.map(month => (
                          <td
                            key={month.label}
                            {...api.getMonthTableCellProps({
                              ...month,
                              columns: 4,
                            })}
                          >
                            <div
                              {...api.getMonthTableCellTriggerProps({
                                ...month,
                                columns: 4,
                              })}
                            >
                              {month.label}
                            </div>
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {/* Year View */}
            {api.view !== 'year' && (
              <div>
                <div {...api.getViewControlProps({ view: 'year' })}>
                  <button {...api.getPrevTriggerProps({ view: 'year' })}>
                    Prev
                  </button>
                  <span>
                    {api.getDecade().start}
                    {' '}
                    -
                    {' '}
                    {api.getDecade().end}
                  </span>
                  <button {...api.getNextTriggerProps({ view: 'year' })}>
                    Next
                  </button>
                </div>

                <table {...api.getTableProps({ view: 'year', columns: 4 })}>
                  <tbody {...api.getTableBodyProps()}>
                    {api.getYearsGrid({ columns: 4 }).map((years, yearIndex) => (
                      <tr key={yearIndex} {...api.getTableRowProps({ view: 'year' })}>
                        {years.map(year => (
                          <td
                            key={year.label}
                            {...api.getYearTableCellProps({
                              ...year,
                              columns: 4,
                            })}
                          >
                            <div
                              {...api.getYearTableCellTriggerProps({
                                ...year,
                                columns: 4,
                              })}
                            >
                              {year.label}
                            </div>
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>,
        document.body,
      )}
    </>
  )
}
