// examples/svelte/src/pages/qr-code.svelte
<script lang="ts">
  import * as qrCode from "@destyler/qr-code"
  import { normalizeProps, useMachine } from "@destyler/svelte"
  import Toolbar from '../components/toolbar.svelte'
  import StateVisualizer from "../components/state-visualizer.svelte"
  import {useControls} from '../hooks/use-controls.svelte'
  import { qrCodeControls } from '@destyler/shared-private'

  const controls = useControls(qrCodeControls)

  const id = $props.id()

  const [state, send] = useMachine(
    qrCode.machine({
      id
    }),
    {
      context: controls.context
    }
  )

  const api = $derived(qrCode.connect(state, send, normalizeProps))
</script>

<div {...api.getRootProps()} class="w-270px h-270px">
  <svg {...api.getFrameProps()} class="w-270px h-270px">
    <path {...api.getPatternProps()} />
  </svg>
  <div {...api.getOverlayProps()} class="w-50px h-50px">
    <img
      src="https://github.com/destyler.png"
      alt=""
    />
  </div>
</div>

<Toolbar {controls}>
  <StateVisualizer state={state} />
</Toolbar>

// examples/react/src/pages/qr-code.tsx
import * as qrCode from '@destyler/qr-code'
import { normalizeProps, useMachine } from '@destyler/react'
import { qrCodeControls } from '@destyler/shared'
import * as React from 'react'
import { useId } from 'react'
import { StateVisualizer } from '../components/tool/StateVisualizer'
import { Toolbar } from '../components/tool/Toolbar'

import { useControls } from '../hooks/use-controls'

export default function QrCode() {
  const controls = useControls(qrCodeControls)

  const [state, send] = useMachine(
    qrCode.machine({
      id: useId(),
    }),
    {
      context: controls.context,
    },
  )

  const api = qrCode.connect(state, send, normalizeProps)

  return (
    <>
      <div {...api.getRootProps()} className="w-270px h-270px">
        <svg {...api.getFrameProps()} className="w-270px h-270px">
          <path {...api.getPatternProps()} />
        </svg>
        <div {...api.getOverlayProps()} className="w-50px h-50px">
          <img
            src="https://github.com/destyler.png"
            alt=""
          />
        </div>
      </div>

      <Toolbar controls={controls.ui()}>
        <StateVisualizer state={state} />
      </Toolbar>
    </>
  )
}
