// packages/components/scroll-area/snippets/ScrollArea.react.tsx
import { normalizeProps, useMachine } from '@destyler/react'
import * as scrollArea from '@destyler/scroll-area'
import { useId } from 'react'
import './style.css'

const tags = Array.from({ length: 50 }).map(
  (_, i, a) => `v1.2.0-beta.${a.length - i}`,
)

export default function ScrollArea() {
  const [state, send] = useMachine(scrollArea.machine({ id: useId() }))

  const api = scrollArea.connect(state, send, normalizeProps)

  return (
    <div {...api.getRootProps()}>
      <div {...api.getViewportProps()}>
        <div {...api.getContentProps()}>
          <div className="scroll-area-header">Tags</div>
          {tags.map(tag => (
            <div key={tag} className="scroll-area-item">
              {tag}
            </div>
          ))}
        </div>
      </div>

      <div {...api.getScrollbarProps({ orientation: 'vertical' })}>
        <div {...api.getThumbProps({ orientation: 'vertical' })} />
      </div>

      <div {...api.getScrollbarProps({ orientation: 'horizontal' })}>
        <div {...api.getThumbProps({ orientation: 'horizontal' })} />
      </div>

      <div {...api.getCornerProps()} />
    </div>
  )
}

// packages/components/scroll-area/snippets/ScrollArea.vue
<script setup lang="ts">
import * as scrollArea from '@destyler/scroll-area'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'
import './style.css'

const tags = Array.from({ length: 50 }).map(
  (_, i, a) => `v1.2.0-beta.${a.length - i}`,
)

const [state, send] = useMachine(scrollArea.machine({ id: useId() }))

const api = computed(() => scrollArea.connect(state.value, send, normalizeProps))
</script>

<template>
  <div v-bind="api.getRootProps()">
    <div v-bind="api.getViewportProps()">
      <div v-bind="api.getContentProps()">
        <div class="scroll-area-header">
          Tags
        </div>
        <div v-for="tag in tags" :key="tag" class="scroll-area-item">
          {{ tag }}
        </div>
      </div>
    </div>

    <div v-bind="api.getScrollbarProps({ orientation: 'vertical' })">
      <div v-bind="api.getThumbProps({ orientation: 'vertical' })" />
    </div>

    <div v-bind="api.getScrollbarProps({ orientation: 'horizontal' })">
      <div v-bind="api.getThumbProps({ orientation: 'horizontal' })" />
    </div>

    <div v-bind="api.getCornerProps()" />
  </div>
</template>
