// packages/components/color-picker/examples/svelte/ColorPicker.svelte
<script lang="ts">
import * as colorPicker from '../../index'
import { normalizeProps, useMachine } from '@destyler/svelte'
import { colorPickerControls } from '@destyler/shared-private'
import {useControls, Toolbar, StateVisualizer, Layout} from '@destyler/shared-private/svelte'
import '../style.css'

const presets = ["#f47373", "#697689"]

const controls = useControls(colorPickerControls)

const id = $props.id();

const [snapshot, send] = useMachine(
  colorPicker.machine({
    id: id,
    name: "color",
    format: "hsla",
    value: colorPicker.parse("hsl(0, 100%, 50%)"),
  }),
  {
    context: controls.context,
  },
)
const api = $derived(colorPicker.connect(snapshot, send, normalizeProps))
</script>

<Layout>
<main class="color-picker">
  <form>
    <input {...api.getHiddenInputProps()} />
    <div {...api.getRootProps()}>
      <label {...api.getLabelProps()}>
        Select Color: <span data-testid="value-text">{api.valueAsString}</span>
      </label>

      <div {...api.getControlProps()}>
        <button {...api.getTriggerProps()}>
          <div {...api.getTransparencyGridProps({ size: "10px" })}></div>
          <div {...api.getSwatchProps({ value: api.value })}></div>
        </button>
        <input {...api.getChannelInputProps({ channel: "hex" })} />
        <input {...api.getChannelInputProps({ channel: "alpha" })} />
      </div>

      <div {...api.getPositionerProps()}>
        <div {...api.getContentProps()}>
          <div class="content__inner">
            <div {...api.getAreaProps()}>
              <div {...api.getAreaBackgroundProps()}></div>
              <div {...api.getAreaThumbProps()}></div>
            </div>

            <div {...api.getChannelSliderProps({ channel: "hue" })}>
              <div {...api.getChannelSliderTrackProps({ channel: "hue" })}></div>
              <div {...api.getChannelSliderThumbProps({ channel: "hue" })}></div>
            </div>

            <div {...api.getChannelSliderProps({ channel: "alpha" })}>
              <div {...api.getTransparencyGridProps({ size: "12px" })}></div>
              <div {...api.getChannelSliderTrackProps({ channel: "alpha" })}></div>
              <div {...api.getChannelSliderThumbProps({ channel: "alpha" })}></div>
            </div>

            {#if api.format.startsWith("hsl")}
              <div style="display:flex;width:100%;">
                <span>H</span> <input {...api.getChannelInputProps({ channel: "hue" })} />
                <span>S</span> <input {...api.getChannelInputProps({ channel: "saturation" })} />
                <span>L</span> <input {...api.getChannelInputProps({ channel: "lightness" })} />
                <span>A</span> <input {...api.getChannelInputProps({ channel: "alpha" })} />
              </div>
            {/if}

            {#if api.format.startsWith("rgb")}
              <div style="display:flex;width:100%;">
                <span>R</span> <input {...api.getChannelInputProps({ channel: "red" })} />
                <span>G</span> <input {...api.getChannelInputProps({ channel: "green" })} />
                <span>B</span> <input {...api.getChannelInputProps({ channel: "blue" })} />
                <span>A</span> <input {...api.getChannelInputProps({ channel: "alpha" })} />
              </div>
            {/if}

            {#if api.format.startsWith("hsb")}
              <div style="display:flex;width:100%;">
                <span>H</span> <input {...api.getChannelInputProps({ channel: "hue" })} />
                <span>S</span> <input {...api.getChannelInputProps({ channel: "saturation" })} />
                <span>B</span> <input {...api.getChannelInputProps({ channel: "brightness" })} />
                <span>A</span> <input {...api.getChannelInputProps({ channel: "alpha" })} />
              </div>
            {/if}

            <div style="display:flex;gap:10px;align-items:center;">
              <div style="position:relative;">
                <div {...api.getTransparencyGridProps({ size: "4px" })}></div>
                <div {...api.getSwatchProps({ value: api.value })}></div>
              </div>
              <p data-testid="value-text">{api.valueAsString}</p>
            </div>

            <input {...api.getChannelInputProps({ channel: "hex" })} />

            <div {...api.getSwatchGroupProps()} style="display:flex;gap:10px;">
              {#each presets as preset}
                <button {...api.getSwatchTriggerProps({ value: preset })}>
                  <div style="position:relative;">
                    <div {...api.getTransparencyGridProps({ size: "4px" })}></div>
                    <div {...api.getSwatchProps({ value: preset })}></div>
                  </div>
                </button>
              {/each}
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</main>

<Toolbar {controls}>
  <StateVisualizer state={snapshot} />
</Toolbar>
</Layout>

// packages/components/color-picker/examples/vue/ColorPicker.vue
<script setup lang="ts">
import { colorPickerControls } from '@destyler/shared-private'
import { Controls, Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/vue'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, ref, useId } from 'vue'
import * as colorPicker from '../../index'
import '../style.css'

const controls = useControls(colorPickerControls)

const [state, send] = useMachine(colorPicker.machine({
  id: useId(),
  name: 'color',
  format: 'hsla',
  value: colorPicker.parse('hsl(0, 100%, 50%)'),
}), {
  context: controls.context,
})

const api = computed(() => colorPicker.connect(state.value, send, normalizeProps))

const presets = ref(['#f47373', '#697689'])
</script>

<template>
  <Layout>
    <main class="color-picker">
      <form>
        <input v-bind="api.getHiddenInputProps()">
        <div v-bind="api.getRootProps()">
          <label v-bind="api.getLabelProps()">
            Select Color: <span data-testid="value-text">{{ api.valueAsString }}</span>
          </label>
        </div>
        <div v-bind="api.getControlProps()">
          <button v-bind="api.getTriggerProps()">
            <div v-bind="api.getTransparencyGridProps({ size: '10px' })" />
            <div v-bind="api.getSwatchProps({ value: api.value })" />
          </button>
          <input v-bind="api.getChannelInputProps({ channel: 'hex' })">
          <input v-bind="api.getChannelInputProps({ channel: 'alpha' })">
        </div>

        <div v-bind="api.getPositionerProps()">
          <div v-bind="api.getContentProps()">
            <div class="content__inner">
              <div v-bind="api.getAreaProps()">
                <div v-bind="api.getAreaBackgroundProps()" />
                <div v-bind="api.getAreaThumbProps()" />
              </div>

              <div v-bind="api.getChannelSliderProps({ channel: 'hue' })">
                <div v-bind="api.getChannelSliderTrackProps({ channel: 'hue' })" />
                <div v-bind="api.getChannelSliderThumbProps({ channel: 'hue' })" />
              </div>

              <div v-bind="api.getChannelSliderProps({ channel: 'alpha' })">
                <div v-bind="api.getTransparencyGridProps({ size: '12px' })" />
                <div v-bind="api.getChannelSliderTrackProps({ channel: 'alpha' })" />
                <div v-bind="api.getChannelSliderThumbProps({ channel: 'alpha' })" />
              </div>

              <div v-if="api.format.startsWith('hsl')" style="display: flex; width: 100%">
                <span>H</span> <input v-bind="api.getChannelInputProps({ channel: 'hue' })"> <span>S</span>
                <input v-bind="api.getChannelInputProps({ channel: 'saturation' })"> <span>L</span>
                <input v-bind="api.getChannelInputProps({ channel: 'lightness' })"> <span>A</span>
                <input v-bind="api.getChannelInputProps({ channel: 'alpha' })">
              </div>

              <div v-if="api.format.startsWith('rgb')" style="display: flex; width: 100%">
                <span>R</span> <input v-bind="api.getChannelInputProps({ channel: 'red' })"> <span>G</span>
                <input v-bind="api.getChannelInputProps({ channel: 'green' })"> <span>B</span>
                <input v-bind="api.getChannelInputProps({ channel: 'blue' })"> <span>A</span>
                <input v-bind="api.getChannelInputProps({ channel: 'alpha' })">
              </div>

              <div v-if="api.format.startsWith('hsb')" style="display: flex; width: 100%">
                <span>H</span> <input v-bind="api.getChannelInputProps({ channel: 'hue' })"> <span>S</span>
                <input v-bind="api.getChannelInputProps({ channel: 'saturation' })"> <span>B</span>
                <input v-bind="api.getChannelInputProps({ channel: 'brightness' })"> <span>A</span>
                <input v-bind="api.getChannelInputProps({ channel: 'alpha' })">
              </div>

              <div style="display: flex; gap: 10px; align-items: center;">
                <div style="position: relative">
                  <div v-bind="api.getTransparencyGridProps({ size: '4px' })" />
                  <div v-bind="api.getSwatchProps({ value: api.value })" />
                </div>
                <p data-testid="value-text">
                  {{ api.valueAsString }}
                </p>
              </div>

              <input v-bind="api.getChannelInputProps({ channel: 'hex' })">

              <div v-bind="api.getSwatchGroupProps()" style="display: flex; gap: 10px">
                <button v-for="preset in presets" :key="preset" v-bind="api.getSwatchTriggerProps({ value: preset })">
                  <div style="position: relative">
                    <div v-bind="api.getTransparencyGridProps({ size: '4px' })" />
                    <div v-bind="api.getSwatchProps({ value: preset })" />
                  </div>
                </button>
              </div>

              <button v-bind="api.getEyeDropperTriggerProps()">
                <EyeDropIcon />
              </button>
            </div>
          </div>
        </div>
      </form>
    </main>

    <Toolbar>
      <StateVisualizer :state="state" />
      <template #controls>
        <Controls :control="controls" />
      </template>
    </Toolbar>
  </Layout>
</template>
