// packages/components/edit/snippets/Edit.react.tsx
import * as edit from '@destyler/edit'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'
import './style.css'

export default function EditPage() {
  const [state, send] = useMachine(edit.machine({
    id: useId(),
    placeholder: 'Type something...',
  }))

  const api = edit.connect(state, send, normalizeProps)

  return (
    <>
      <div {...api.getRootProps()}>
        <div {...api.getAreaProps()}>
          <input {...api.getInputProps()} />
          <span {...api.getPreviewProps()} />
        </div>
        <div className="flex justify-end gap-2 mt-0!">
          {api.editing
            ? (
                <>
                  <button {...api.getSubmitTriggerProps()}>
                    Save
                  </button>
                  <button {...api.getCancelTriggerProps()}>
                    Cancel
                  </button>
                </>
              )
            : (
                <button {...api.getEditTriggerProps()}>
                  Edit
                </button>
              )}
        </div>
      </div>
    </>
  )
}

// packages/components/edit/snippets/Edit.svelte
<script lang="ts">
  import * as edit from "@destyler/edit";
  import { normalizeProps, useMachine } from "@destyler/svelte";
  import './style.css'

  const [state, send] = useMachine(edit.machine({
    id: crypto.randomUUID(),
    placeholder: 'Type something...',
  }))

  const api = $derived(edit.connect(state, send, normalizeProps));
</script>

<div {...api.getRootProps()} >
  <div {...api.getAreaProps()} >
    <input {...api.getInputProps()} />
    <span {...api.getPreviewProps()}></span>
  </div>
  <div class="flex justify-end gap-2 mt-0!">
    {#if api.editing}
      <button {...api.getSubmitTriggerProps()} >
        Save
      </button>
      <button {...api.getCancelTriggerProps()} >
        Cancel
      </button>
    {:else}
      <button {...api.getEditTriggerProps()}>
        Edit
      </button>
    {/if}
  </div>
</div>
