// packages/components/file-upload/examples/vue/FileUpload.vue
<script setup lang="ts">
import { fileUploadControls } from '@destyler/shared-private'
import { Controls, Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/vue'
import { normalizeProps, useMachine } from '@destyler/vue'
import { computed, useId } from 'vue'
import * as fileUpload from '../../index'
import '../style.css'

const controls = useControls(fileUploadControls)

const [state, send] = useMachine(fileUpload.machine({ id: useId() }), {
  context: controls.context,
})

const api = computed(() =>
  fileUpload.connect(state.value, send, normalizeProps),
)
</script>

<template>
  <Layout>
    <div v-bind="api.getRootProps()">
      <div v-bind="api.getDropzoneProps()">
        <input v-bind="api.getHiddenInputProps()">
        <p>
          Drag and drop your files here
        </p>
        <p>
          or
        </p>
        <button v-bind="api.getTriggerProps()">
          Choose Files...
        </button>
      </div>

      <ul
        v-bind="api.getItemGroupProps()"
      >
        <li
          v-for="file in api.acceptedFiles"
          :key="file.name"
          v-bind="api.getItemProps({ file })"
        >
          <div v-bind="api.getItemNameProps({ file })">
            {{ file.name }}
          </div>
          <button v-bind="api.getItemDeleteTriggerProps({ file })">
            Delete
          </button>
        </li>
      </ul>
    </div>
    <Toolbar>
      <StateVisualizer :state="state" />
      <template #controls>
        <Controls :control="controls" />
      </template>
    </Toolbar>
  </Layout>
</template>

// packages/components/file-upload/examples/react/FileUpload.react.tsx
import { normalizeProps, useMachine } from '@destyler/react'
import { fileUploadControls } from '@destyler/shared-private'
import { Layout, StateVisualizer, Toolbar, useControls } from '@destyler/shared-private/react'
import { useId } from 'react'
import * as fileUpload from '../../index'
import '../style.css'

export default function FileUpload() {
  const controls = useControls(fileUploadControls)

  const [state, send] = useMachine(fileUpload.machine({ id: useId() }), {
    context: controls.context,
  })

  const api = fileUpload.connect(state, send, normalizeProps)

  return (
    <Layout>
      <div {...api.getRootProps()}>
        <div
          {...api.getDropzoneProps()}
        >
          <input {...api.getHiddenInputProps()} />
          <p>Drag and drop your files here</p>
          <p>or</p>
          <button
            {...api.getTriggerProps()}
          >
          Choose Files...
          </button>
        </div>

        <ul
          {...api.getItemGroupProps()}
        >
          {api.acceptedFiles.map(file => (
            <li
              key={file.name}
              {...api.getItemProps({ file })}
            >
              <div
                {...api.getItemNameProps({ file })}
              >
                {file.name}
              </div>
              <button
                {...api.getItemDeleteTriggerProps({ file })}
              >
              Delete
              </button>
            </li>
          ))}
        </ul>
      </div>
      <Toolbar controls={controls.ui()}>
        <StateVisualizer state={state} />
      </Toolbar>
    </Layout>
  )
}
